---
title: "Taking Uncertainty Seriously: Bayesian Marginal Structural Models for Causal Inference in Political Science"
date: 2023-02-01
author:
  - name: Andrew Heiss
    url: https://www.andrewheiss.com/
    orcid: 0000-0002-3948-3914
    affiliation: Andrew Young School of Policy Studies, Georgia State University
  - name: A. Jordan Nafa
    url: https://www.ajordannafa.com/
    orcid: 0000-0001-5574-3950
    affiliation: University of North Texas
categories: 
  - Causal inference
  - Bayes
  - Panel data
  - Methods
pub-info:
  reference: >-
    <strong>Andrew Heiss</strong> and <a href="https://www.ajordannafa.com/">A. Jordan Nafa</a>, “Taking Uncertainty Seriously: Bayesian Marginal Structural Models for Causal Inference in Political Science”
  links:
  - name: Code
    url: https://github.com/ajnafa/Latent-Bayesian-MSM
    icon: fa-brands fa-github
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
#   status: Under review
#   class: success
#   icon: fas fa-glasses
---

## Important links

- [GitHub repository](https://github.com/ajnafa/Latent-Bayesian-MSM)


## Abstract

The past two decades have been characterized by considerable progress in developing approaches to causal inference in situations where true experimental manipulation is either impractical or impossible. With few exceptions, however, commonly employed techniques in political science have developed largely within the frequentist framework (i.e., Blackwell and Glynn 2018; Imai and Kim 2019; Torres 2020). In this article, we argue that common approaches rest fundamentally upon assumptions that are difficult to defend in many areas of political research and highlight the benefits of quantifying uncertainty in the estimation of causal effects (Gill 1999; Gill and Heuberger 2020; Schrodt 2014; Western and Jackman 1994). Extending the approach to causal inference for cross-sectional time series and panel data under selection on observables introduced by Blackwell and Glynn (2018), we develop a two-step Bayesian approach to the estimation of marginal structural models. We demonstrate our proposed procedure in the context of parametric survival analysis and linear mixed effects models via a simulation study and two empirical examples. Finally, we provide flexible open-source software implementing the proposed method.


## BibTeX citation

```bibtex
@unpublished{HeissNafa:2022,
    Author = {Andrew Heiss and A. Jordan Nafa},
    Note = {Working paper},
    Title = {Taking Uncertainty Seriously: Bayesian Marginal Structural Models for Causal Inference in Political Science},
    Year = {2022}}
```
