---
title: "Clarifying Correlation and Causation: A Guide to Modern Quantitative Causal Inference in Nonprofit Studies"
date: 2021-10-03
author:
  - name: Andrew Heiss
    url: https://www.andrewheiss.com/
    orcid: 0000-0002-3948-3914
    affiliation: Andrew Young School of Policy Studies, Georgia State University
  - name: Meng Ye
    orcid: 0000-0002-6552-8338
    affiliation: Andrew Young School of Policy Studies, Georgia State University
categories: 
  - Causal inference
  - Nonprofits
  - Methods
pub-info:
  reference: >-
    <strong>Andrew Heiss</strong> and <a href="https://aysps.gsu.edu/phd-student/ye-meng/">Meng Ye</a>, “Clarifying Correlation and Causation: A Guide to Modern Quantitative Causal Inference in Nonprofit Studies”
  links:
  - name: Code
    url: https://github.com/andrewheiss/corrupt-caterpillar
    icon: fa-brands fa-github
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
#   status: Under review
#   class: success
#   icon: fas fa-glasses
---

## Important links

- [GitHub repository](https://github.com/andrewheiss/corrupt-caterpillar)


## Abstract

Discovering causal relationships and testing theoretical mechanisms is a core endeavor of social science. Randomized experiments have long served as a gold standard for making valid causal inferences, but most of the data social scientists work with is observational and non-experimental. However, with newer methodological developments in economics, political science, epidemiology, and other disciplines, an increasing number of studies in social science make causal claims with observational data. As a newer interdisciplinary field, however, nonprofit studies has lagged behind other disciplines in its use of observational causal inference. In this article, we present a hands-on introduction and guide to design-based observational causal inference methods. We first review and categorize all studies making causal claims in top nonprofit studies journals over the past decade to illustrate the field’s current of experimental and observational approaches to causal inference. We then introduce a framework for modeling and identifying causal processes using directed acyclic graphs (DAGs) and provide a walk-through of the assumptions and procedures for making inferences with a range of different methods, including matching, inverse probability weighting, difference-in-differences, regression discontinuity designs, and instrumental variables. We illustrate each approach with synthetic and empirical examples and provide sample R and Stata code for implementing these methods. We conclude by encouraging scholars and practitioners to make more careful and explicit causal claims in their observational empirical research, collectively developing and improving quantitative work in the broader field of nonprofit studies.
