{
  "hash": "f6f9c0ba5ea9d1f948cfc641370b6466",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Demystifying causal inference estimands: ATE, ATT, and ATU\"\ndate: 2024-03-21\ndescription: \"Explore why we care about the ATE, ATT, and ATU and figure out how to calculate them with observational data\"\nimage: \"index_files/figure-html/fig-propensity-weighted-ate-1.png\"\ntwitter-card:\n  image: \"index_files/figure-html/fig-propensity-weighted-ate-1.png\"\nopen-graph:\n  image: \"index_files/figure-html/fig-propensity-weighted-ate-1.png\"\ncategories:\n  - r\n  - tidyverse\n  - causal inference\n  - DAGs\n  - inverse probability weighting\nresources:\n  - \"mosquito_nets_v2.csv\"\nbibliography: references.json\ncsl: chicago-author-date.csl\ninclude-before-body:\n  text: |\n    <style>\n      .no-stripe .gt_table tr.odd {\n        --bs-table-striped-bg: transparent;\n      }\n      \n      .gt_footnote {\n        text-align: left !important;\n      }\n    </style>\n# doi: 10.59350/pe5s8-e0f47\n---\n\n\n\n\nIn [my causal inference class](https://evalsp24.classes.andrewheiss.com/), I spend [just one week](https://evalsp24.classes.andrewheiss.com/content/05-content.html) talking about the [Rubin causal model](https://en.wikipedia.org/wiki/Rubin_causal_model) and potential outcomes. This view of causality argues that for any kind of intervention (passing a new policy, participation in a nonprofit program, taking a specific kind of medicine, etc.), people will have one of two possible outcomes: \n\n1. What would happen if they receive the intervention or treatment, and \n2. What would happen if they do not receive the treatment\n\nThese two outcomes are *potential outcomes*. Both are plausible, but only one will happen in real life. These potential outcomes lead to a bunch of different causal estimands we might be interested in in, like the average treatment effect.\n\nI give such short shrift to potential outcomes largely because the bulk of the class approaches the idea of causal inference through Judea Pearl-style DAGs instead of potential outcomes. It's a strange arrangement that I've stumbled into: the potential outcomes approach is incredibly popular and widespread in social sciences (particularly in economics), while causal models and DAGs are more popular in fields like epidemiology. For unfathomable reasons, there's a weird animosity between these two worlds. Judea Pearl regularly needles social scientists on Twitter for not using DAGs and clinging to potential outcomes, while Nobel-winning econometricians decry DAGs. It's weird.[^dag-econ]\n\n[^dag-econ]: Though [this neat paper by a DAG-using economist](https://doi.org/10.1080/1350178X.2022.2088085) tries to bridge that gap [@Huntington-Klein:2022].\n\nAs a social scientist myself, you'd think I'd have embraced the potential outcomes approach, but for whatever reason, it never stuck and it was always confusing to me. When I came across Judea Pearl's *The Book of Why* [@PearlMackenzie:2020] a few years ago, I fell in love with the world of DAGs. They made sense—far more sense than the weird decompositional algebra behind average treatment effects, average treatment on the treated effects, average treatment on the untreated effects, and so on.\n\nI'm not the only social science convert to DAGs. The general social science methods textbook [*Counterfactuals and Causal Inference*](https://www.cambridge.org/core/books/counterfactuals-and-causal-inference/5CC81E6DF63C5E5A8B88F79D45E1D1B7) [@MorganWinship:2014] started popularizing DAGs in 2007, two modern phenomenal econometrics textbooks—[*The Effect*](https://theeffectbook.net/) [@Huntington-Klein:2021] and [*Causal Inference: The Mixtape*](https://mixtape.scunning.com/) [@Cunningham:2021]—feature DAGs throughout (despite that discipline's weird aversion to them), and the latest version of the fantastic Bayesian [*Statistical Rethinking*](https://xcelab.net/rm/statistical-rethinking/) [@McElreath:2020] uses them extensively.\n\nDespite all these newer DAG-based approaches in social science, in my class, I never really revisit the potential outcomes framework after that one week. We do all sorts of causal effects estimation with DAG-based adjustment through matching and inverse probability weighting, and quasi-experimental design-based approaches like difference-in-differences, regression discontinuity, and instrumental variables, but beyond emphasizing the fact that methods like regression discontinuity and instrumental variables only return *local* average treatment effects, we don't really ever talk about ATEs and ATTs and ATUs again.\n\nThis has always bugged me.\n\nBeyond introducing the idea that we can't find individual-level causal effects without a time machine, thinking about potential outcomes is neat, I guess, but not exactly relevant to all the other methods we cover. **I know that's wrong!** But that's how my mental model of these estimands has worked. All these other methods give some sort of general average causal effect, but I'm never sure which exact flavor of causal effect it is (or if the exact flavor matters).\n\nBut [a newer working paper](https://arxiv.org/abs/2106.10577) by @GreiferStuart:2023 has finally helped me realize why these different estimands matter and what the subtle differences between them are.\n\nSo in this post, I'll extend the basic standard ATE/ATT/ATU example to reflect a more realistic, larger dataset, and I'll use propensity score weighting to estimate each estimand. I'll also follow Greifer and Stuart's example and translate these estimands into policy-relevant English equivalents (they use medical terminology; I'm not that kind of doctor and I work with social science and policy interventions).\n\nBut first, I *highly* recommend [reading through their paper really quick](https://arxiv.org/abs/2106.10577). It's not too long and and it's not too mathy—it's succinct and accessible and a good primer for all these estimands.\n\n(And before we start, let's load some R packages.)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggtext)\nlibrary(ggdag)\nlibrary(dagitty)\nlibrary(gt)\nlibrary(broom)\nlibrary(marginaleffects)\nlibrary(WeightIt)\n\n# Define a nice color palette from {MoMAColors}\n# https://github.com/BlakeRMills/MoMAColors\nclrs <- MoMAColors::moma.colors(\"ustwo\")\n\n# Download Mulish from https://fonts.google.com/specimen/Mulish\ntheme_nice <- function() {\n  theme_minimal(base_family = \"Mulish\") +\n    theme(\n      panel.grid.minor = element_blank(),\n      plot.background = element_rect(fill = \"white\", color = NA),\n      plot.title = element_text(face = \"bold\"),\n      axis.title = element_text(face = \"bold\"),\n      strip.text = element_text(face = \"bold\"),\n      strip.background = element_rect(fill = \"grey80\", color = NA),\n      legend.title = element_text(face = \"bold\")\n    )\n}\n\ntheme_set(theme_nice())\n\nupdate_geom_defaults(\"text\", list(family = \"Mulish\", fontface = \"plain\"))\nupdate_geom_defaults(\"label\", list(family = \"Mulish\", fontface = \"plain\"))\nupdate_geom_defaults(ggdag:::GeomDagText, list(family = \"Mulish\", fontface = \"plain\"))\nupdate_geom_defaults(ggtext::GeomRichText, list(family = \"Mulish\", fontface = \"plain\"))\n```\n:::\n\n\n# Quick crash course in potential outcomes\n\nBefore getting into the subtle differences between the various potential outcomes-related estimands, it's helpful to get a general sense for how these things work. So let's take a super abbreviated crash course in the potential outcomes framework.\n\nEvery causal inference textbook ever written will include a table like @tbl-basic-po to illustrate potential outcomes. To make this idea a little more mathy, we'll call the treatment or intervention $X$, the outcome that would happen if treated $Y^1$, and the outcome that would happen if not treated $Y^0$.[^po-notation] We'll use $\\delta$ for the difference between $Y^1$ and $Y^0$, or the individual-level causal effect.\n\n[^po-notation]: The notation for all this varies wildly across disciplines. Economists call the treatment $D$ for mysterious reasons; epidemiologists will often call it $A$; I've seen political science papers call it $T$ (which at least makes more sense than $D$ or $A$, since \"treatment\" starts with T). In my class I call it $X$, which follows what a lot of other people do (like this guide to [\"10 Strategies for Figuring Out if X Caused Y\"](https://egap.org/resource/10-strategies-for-figuring-out-if-x-caused-y/)).\n\n\n::: {#tbl-basic-po .cell .no-stripe layout-align=\"center\" tbl-cap='Standard table showing potential outcomes, individual causal effects, and realized outcomes'}\n\n```{.r .cell-code  code-fold=\"true\"}\nbasic_po <- tribble(\n  ~id, ~age,    ~treated, ~outcome_1, ~outcome_0,\n  1,   \"Old\",   1,        80,         60,\n  2,   \"Old\",   1,        75,         70,\n  3,   \"Old\",   1,        85,         80,\n  4,   \"Old\",   0,        70,         60,\n  5,   \"Young\", 1,        75,         70,\n  6,   \"Young\", 0,        80,         80,\n  7,   \"Young\", 0,        90,         100,\n  8,   \"Young\", 0,        85,         80\n) |> \n  mutate(\n    ice = outcome_1 - outcome_0,\n    outcome = ifelse(treated == 1, outcome_1, outcome_0)\n  )\n\nbasic_po |> \n  select(\n    id, age, treated, outcome_1, outcome_0, ice, outcome\n  ) |> \n  gt() |> \n  sub_missing(missing_text = \"…\") |>\n  fmt_number(\n    columns = c(starts_with(\"outcome\"), ice),\n    decimals = 0\n  ) |> \n\n  # Column labels\n  cols_label(\n    id = \"ID\",\n    age = md(\"$Z_i$\"),\n    treated = md(\"$X_i$\"),\n    outcome_0 = md(\"$Y^0_i$\"),\n    outcome_1 = md(\"$Y^1_i$\"),\n    outcome = md(\"$Y_i$\"),\n    ice = md(\"$Y^1_i - Y^0_i$\")\n  ) |>\n  \n  # Level 1 spanner labels\n  tab_spanner(\n    label = \"Age\", columns = age, \n    level = 1, id = \"level1_a_po\"\n  ) |> \n  tab_spanner(\n    label = \"Treated\", columns = treated, \n    level = 1, id = \"level1_b_po\"\n  ) |> \n  tab_spanner(\n    label = \"Potential outcomes\",\n    columns = c(outcome_1, outcome_0),\n    level = 1, id = \"level1_c_po\"\n  ) |> \n  tab_spanner(\n    label = \"ICE or \\\\(\\\\delta_i\\\\)\", columns = ice, \n    level = 1, id = \"level1_d_po\"\n  ) |> \n  tab_spanner(\n    label = \"Outcome\", columns = outcome, \n    level = 1, id = \"level1_e_po\"\n  ) |> \n  \n  # Level 2 spanner labels\n  tab_spanner(\n    label = \"Confounder\",\n    columns = age,\n    level = 2, id = \"level2_a_po\"\n  ) |> \n  tab_spanner(\n    label = \"Treatment\", columns = treated, \n    level = 2, id = \"level2_b_po\"\n  ) |> \n  tab_spanner(\n    label = \"Unobservable\",\n    columns = c(outcome_1, outcome_0, ice), \n    level = 2, id = \"level2_c_po\"\n  ) |> \n  tab_spanner(\n    label = \"Realized\", columns = outcome, \n    level = 2, id = \"level2_d_po\") |> \n  \n  # Style stuff\n  tab_style(\n    style = cell_text(align = \"center\"),\n    locations = cells_column_labels()\n  ) |> \n  tab_style(\n    style = cell_text(align = \"center\"),\n    locations = cells_body()\n  ) |> \n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = list(\n      cells_column_spanners(spanners = starts_with(\"level1\")),\n      cells_column_labels(columns = \"id\")\n    )\n  ) |> \n  tab_style(\n    style = cell_text(style = \"italic\"),\n    locations = cells_column_spanners(spanners = starts_with(\"level2\"))\n  ) |> \n  \n  tab_style(\n    style = list(\n      cell_fill(color = clrs[4], alpha = 0.5)\n    ),\n    locations = cells_body(rows = treated == 1)\n  ) |> \n  tab_footnote(\n    footnote = \"ICE = individual causal effect\",\n    locations = cells_column_spanners(spanners = \"level1_d_po\")\n  ) |> \n  opt_footnote_marks(marks = \"standard\") |> \n  opt_horizontal_padding(scale = 3) |> \n  opt_table_font(font = \"Jost\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dngtmfhwcg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dngtmfhwcg table {\n  font-family: Jost, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dngtmfhwcg thead, #dngtmfhwcg tbody, #dngtmfhwcg tfoot, #dngtmfhwcg tr, #dngtmfhwcg td, #dngtmfhwcg th {\n  border-style: none;\n}\n\n#dngtmfhwcg p {\n  margin: 0;\n  padding: 0;\n}\n\n#dngtmfhwcg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dngtmfhwcg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dngtmfhwcg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dngtmfhwcg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 15px;\n  padding-right: 15px;\n  overflow-x: hidden;\n}\n\n#dngtmfhwcg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dngtmfhwcg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dngtmfhwcg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dngtmfhwcg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dngtmfhwcg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dngtmfhwcg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dngtmfhwcg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dngtmfhwcg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dngtmfhwcg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dngtmfhwcg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dngtmfhwcg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#dngtmfhwcg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n  vertical-align: top;\n}\n\n#dngtmfhwcg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dngtmfhwcg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dngtmfhwcg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#dngtmfhwcg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dngtmfhwcg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#dngtmfhwcg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dngtmfhwcg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#dngtmfhwcg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dngtmfhwcg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#dngtmfhwcg .gt_left {\n  text-align: left;\n}\n\n#dngtmfhwcg .gt_center {\n  text-align: center;\n}\n\n#dngtmfhwcg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dngtmfhwcg .gt_font_normal {\n  font-weight: normal;\n}\n\n#dngtmfhwcg .gt_font_bold {\n  font-weight: bold;\n}\n\n#dngtmfhwcg .gt_font_italic {\n  font-style: italic;\n}\n\n#dngtmfhwcg .gt_super {\n  font-size: 65%;\n}\n\n#dngtmfhwcg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dngtmfhwcg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dngtmfhwcg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dngtmfhwcg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dngtmfhwcg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dngtmfhwcg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dngtmfhwcg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dngtmfhwcg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Confounder\">\n        <span class=\"gt_column_spanner\">Confounder</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Treatment\">\n        <span class=\"gt_column_spanner\">Treatment</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"colgroup\" id=\"Unobservable\">\n        <span class=\"gt_column_spanner\">Unobservable</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Realized\">\n        <span class=\"gt_column_spanner\">Realized</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" style=\"text-align: center; font-weight: bold;\" scope=\"col\" id=\"ID\">ID</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Age\">\n        <span class=\"gt_column_spanner\">Age</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Treated\">\n        <span class=\"gt_column_spanner\">Treated</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"Potential outcomes\">\n        <span class=\"gt_column_spanner\">Potential outcomes</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"ICE or \\(\\delta_i\\)&lt;span class=&quot;gt_footnote_marks gt_asterisk&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;*&lt;/sup&gt;&lt;/span&gt;\">\n        <span class=\"gt_column_spanner\">ICE or \\(\\delta_i\\)<span class=\"gt_footnote_marks gt_asterisk\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>*</sup></span></span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Outcome\">\n        <span class=\"gt_column_spanner\">Outcome</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Z_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Z_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Z_i$\"><div class='gt_from_md'><p>\\(Z_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$X_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(X_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$X_i$\"><div class='gt_from_md'><p>\\(X_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y^1_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y^1_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y^1_i$\"><div class='gt_from_md'><p>\\(Y^1_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y^0_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y^0_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y^0_i$\"><div class='gt_from_md'><p>\\(Y^0_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y^1_i - Y^0_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y^1_i - Y^0_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y^1_i - Y^0_i$\"><div class='gt_from_md'><p>\\(Y^1_i - Y^0_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y_i$\"><div class='gt_from_md'><p>\\(Y_i\\)</p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">Old</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"outcome_1\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">80</td>\n<td headers=\"outcome_0\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">60</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">20</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">80</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">2</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">Old</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"outcome_1\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">75</td>\n<td headers=\"outcome_0\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">70</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">5</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">75</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">3</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">Old</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"outcome_1\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">85</td>\n<td headers=\"outcome_0\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">80</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">5</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">85</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">4</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center;\">Old</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">70</td>\n<td headers=\"outcome_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">60</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">10</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center;\">60</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">5</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">Young</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"outcome_1\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">75</td>\n<td headers=\"outcome_0\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">70</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">5</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">75</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">6</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center;\">Young</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">80</td>\n<td headers=\"outcome_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">80</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center;\">80</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">7</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center;\">Young</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">90</td>\n<td headers=\"outcome_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">100</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">−10</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center;\">100</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">8</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center;\">Young</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">85</td>\n<td headers=\"outcome_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">80</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">5</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center;\">80</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"7\"><span class=\"gt_footnote_marks gt_asterisk\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>*</sup></span> ICE = individual causal effect</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Individual-level causal effects (ICE or $\\delta$)\n\nEach person in @tbl-basic-po has two potential outcomes. Person 1, for instance, would have an outcome of 80 ($Y^1$) if they receive the treatment $X$, but only an outcome of 60 ($Y^0$) if they don't. Their *individual-level causal effect* ($\\delta$) is 20. This represents the effect of the treatment for just that one person, and it's only measurable with a time machine or some way to observe parallel universes.\n\n## Average treatment effects (ATE)\n\nIf we could compare all these people in Universe A and Universe B and measure their individual causal effects, we could calculate the *average treatment effect* (ATE), or the effect of the intervention across the whole population. Officially, the ATE is the average of the $\\delta$ column, or the average of $Y^1 - Y^0$:\n\n$$\n\\begin{aligned}\n\\text{ATE} &= E[\\delta_i] & \\text{ or} \\\\\n\\text{ATE} &= E[Y^1_i - Y^0_i]\n\\end{aligned}\n$$\n\nGiven the data in @tbl-basic-po, the ATE is 5—it's the average of the $\\delta$ column:\n\n$$\n\\text{ATE} = \\frac{20 + 5 + 5 + 5 + 10 + 0 + -10 + 5}{8} = 5\n$$\n\nNeat.\n\n## Average treatment effect on the treated (ATT)\n\nThere are a couple other causal effects we can measure. We might want to know how big the effect is just for those who received the treatment. This is called the *average treatment effect on the treated* (ATT), and is the average of the individual causal effects just among those who were treated. Officially, it's defined like this:\n\n$$\n\\begin{aligned}\n\\text{ATT} &= E[\\delta_i \\mid X_i = 1] & \\text{or} \\\\\n\\text{ATT} &= E[Y^1_i - Y^0_i \\mid X_i = 1]\n\\end{aligned}\n$$\n\nIn this case, that means we're only looking at the average $\\delta$ for rows 1, 2, 3, and 5 in @tbl-basic-po:\n\n$$\n\\text{ATT} = \\frac{20 + 5 + 5 + 5}{4} = 8.75\n$$\n\n## Average treatment effect on the untreated (ATU)\n\nWe can also calculate the *average treatment effect on the untreated* (ATU; sometimes called the ATC (for effect on the control group)) by finding the average of the individual causal effects among those who were not treated:\n\n$$\n\\begin{aligned}\n\\text{ATU} &= E[\\delta_i \\mid X_i = 0] & \\text{or} \\\\\n\\text{ATU} &= E[Y^1_i - Y^0_i \\mid X_i = 0]\n\\end{aligned}\n$$\n\nHere, we're only looking at the average $\\delta$ for rows 4, 6, 7, and 8 in @tbl-basic-po:\n\n$$\n\\text{ATU} = \\frac{10 + 0 - 10 + 5}{4} = 1.25\n$$\n\n## Selection bias\n\nThere's a neat relationship between the ATE, ATT, and ATU—the ATE is technically a weighted average of the ATT added to the weighted average of the ATU (here $\\pi$ means \"proportion\", not 3.1415):\n\n$$\n\\text{ATE} = (\\pi_\\text{Treated} \\times \\text{ATT}) + (\\pi_\\text{Untreated} \\times \\text{ATU})\n$$\n\nApplying this to @tbl-basic-po, we can get the same ATE:\n\n$$\n\\begin{aligned}\n\\text{ATE} &= (\\frac{4}{8} \\times 8.75) + (\\frac{4}{8} \\times 1.25) \\\\\n&= 4.375 + 0.625 \\\\\n&= 5\n\\end{aligned}\n$$\n\nOne reason it's helpful to decompose the ATE into these two parts like this is that it shows that there's some systematic difference between the treated and untreated people. This difference is called *selection bias*. People who chose to be treated did so for reasons known only to them.[^mind-reading] \n\n[^mind-reading]: Not only do we need a time machine for good causal inference, we also need a machine that can read minds.\n\nWe can see the selection bias in an alternative decomposition of the ATE:\n\n$$\n\\text{ATE} = \\text{ATT} + \\text{Selection bias}\n$$\n\nThe fact that the ATT (8.75) is bigger than the ATE (5) here is a sign the two groups are different. This intervention, whatever it is, has a big effect on the treated people who signed up for it, likely because they somehow knew that the intervention would be helpful for them. Those who were untreated have a really low ATU (1.25)—they likely didn't sign up for the intervention because they knew that it wouldn't do much for them.\n\n## Finding the ATE from observational data\n\nThis is all well and good, but we don't have time machines. This is the *fundamental problem of causal inference*—we have no idea what each person's $\\delta$ is. We actually only see this in real life:\n\n\n::: {#tbl-basic-realized .cell .no-stripe layout-align=\"center\" tbl-cap='Observed version of @tbl-basic-po showing only the realized outcome'}\n\n```{.r .cell-code  code-fold=\"true\"}\nbasic_po |> \n  select(\n    id, age, treated, outcome\n  ) |> \n  gt() |> \n  fmt_number(\n    columns = \"outcome\",\n    decimals = 0\n  ) |> \n\n  # Column labels\n  cols_label(\n    id = \"ID\",\n    age = md(\"$Z_i$\"),\n    treated = md(\"$X_i$\"),\n    outcome = md(\"$Y_i$\")\n  ) |>\n  \n  # Level 1 spanner labels\n  tab_spanner(\n    label = \"Age\", columns = age, \n    level = 1, id = \"level1_a_po_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Treated\", columns = treated, \n    level = 1, id = \"level1_b_po_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Outcome\", columns = outcome, \n    level = 1, id = \"level1_c_po_obs\"\n  ) |> \n  \n  # Level 2 spanner labels\n  tab_spanner(\n    label = \"Confounder\",\n    columns = age,\n    level = 2, id = \"level2_a_po_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Treatment\", columns = treated, \n    level = 2, id = \"level2_b_po_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Realized\", columns = outcome, \n    level = 2, id = \"level2_c_po_obs\") |> \n  \n  # Style stuff\n  tab_style(\n    style = cell_text(align = \"center\"),\n    locations = cells_column_labels()\n  ) |> \n  tab_style(\n    style = cell_text(align = \"center\"),\n    locations = cells_body()\n  ) |> \n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = list(\n      cells_column_spanners(spanners = starts_with(\"level1\")),\n      cells_column_labels(columns = \"id\")\n    )\n  ) |> \n  tab_style(\n    style = cell_text(style = \"italic\"),\n    locations = cells_column_spanners(spanners = starts_with(\"level2\"))\n  ) |> \n\n  tab_style(\n    style = list(\n      cell_fill(color = clrs[4], alpha = 0.5)\n    ),\n    locations = cells_body(rows = treated == 1)\n  ) |> \n  opt_horizontal_padding(scale = 3) |> \n  opt_table_font(font = \"Jost\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wuwphjtivl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wuwphjtivl table {\n  font-family: Jost, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wuwphjtivl thead, #wuwphjtivl tbody, #wuwphjtivl tfoot, #wuwphjtivl tr, #wuwphjtivl td, #wuwphjtivl th {\n  border-style: none;\n}\n\n#wuwphjtivl p {\n  margin: 0;\n  padding: 0;\n}\n\n#wuwphjtivl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wuwphjtivl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wuwphjtivl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wuwphjtivl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 15px;\n  padding-right: 15px;\n  overflow-x: hidden;\n}\n\n#wuwphjtivl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wuwphjtivl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wuwphjtivl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wuwphjtivl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wuwphjtivl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wuwphjtivl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wuwphjtivl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wuwphjtivl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wuwphjtivl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wuwphjtivl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wuwphjtivl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#wuwphjtivl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n  vertical-align: top;\n}\n\n#wuwphjtivl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wuwphjtivl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wuwphjtivl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#wuwphjtivl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wuwphjtivl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#wuwphjtivl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wuwphjtivl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#wuwphjtivl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wuwphjtivl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#wuwphjtivl .gt_left {\n  text-align: left;\n}\n\n#wuwphjtivl .gt_center {\n  text-align: center;\n}\n\n#wuwphjtivl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wuwphjtivl .gt_font_normal {\n  font-weight: normal;\n}\n\n#wuwphjtivl .gt_font_bold {\n  font-weight: bold;\n}\n\n#wuwphjtivl .gt_font_italic {\n  font-style: italic;\n}\n\n#wuwphjtivl .gt_super {\n  font-size: 65%;\n}\n\n#wuwphjtivl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wuwphjtivl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wuwphjtivl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wuwphjtivl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wuwphjtivl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wuwphjtivl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wuwphjtivl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wuwphjtivl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Confounder\">\n        <span class=\"gt_column_spanner\">Confounder</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Treatment\">\n        <span class=\"gt_column_spanner\">Treatment</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Realized\">\n        <span class=\"gt_column_spanner\">Realized</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" style=\"text-align: center; font-weight: bold;\" scope=\"col\" id=\"ID\">ID</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Age\">\n        <span class=\"gt_column_spanner\">Age</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Treated\">\n        <span class=\"gt_column_spanner\">Treated</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Outcome\">\n        <span class=\"gt_column_spanner\">Outcome</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Z_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Z_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Z_i$\"><div class='gt_from_md'><p>\\(Z_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$X_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(X_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$X_i$\"><div class='gt_from_md'><p>\\(X_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y_i$\"><div class='gt_from_md'><p>\\(Y_i\\)</p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">Old</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">80</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">2</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">Old</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">75</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">3</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">Old</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">85</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">4</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center;\">Old</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center;\">60</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">5</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">Young</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">75</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">6</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center;\">Young</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center;\">80</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">7</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center;\">Young</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center;\">100</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">8</td>\n<td headers=\"age\" class=\"gt_row gt_left\" style=\"text-align: center;\">Young</td>\n<td headers=\"treated\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"outcome\" class=\"gt_row gt_right\" style=\"text-align: center;\">80</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nWe could try to find the ATE by finding the average outcome among the treated ($\\bar{Y}_\\text{Treated}$) and subtracting it from the average outcome among the untreated ($\\bar{Y}_\\text{Untreated}$):\n\n$$\n\\begin{aligned}\n\\text{ATE}_\\text{naive} &= \\bar{Y}_\\text{Treated} - \\bar{Y}_\\text{Untreated} \\\\\n&= \\frac{80 + 75 + 85 + 75}{4} - \\frac{60 + 80 + 100 + 80}{4} \\\\\n&= 78.75 - 80 \\\\\n&= -1.25\n\\end{aligned}\n$$\n\nBut this is horribly wrong. Selection bias is distorting the causal effect here. Treated people sought out treatment because they knew it would be good for them. We can't compare the two groups directly like this because of the systematic differences between them.\n\nWe need to somehow account for the fact that the two groups are different. We've been ignoring one column in this table all this time—age ($Z$). It looks like age is highly correlated with treatment status here. 75% of people who signed up for the treatment were old; 75% of people who didn't sign up for the treatment were young.[^treatment-type] In DAG terms, age seems to be a confounder—it causes both the choice to receive treatment and the ultimate value of the outcome. Age opens up a backdoor relationship between treatment and outcome and messes up the causal effect. If we can somehow statistically account for age, we'll be left with a more accurate estimate of the actual ATE.\n\n[^treatment-type]: Maybe this treatment is a colonoscopy? idk—use your imagination.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nbasic_dag <- dagify(\n  Y ~ X + Z,\n  X ~ Z,\n  exposure = \"X\",\n  outcome = \"Y\",\n  coords = list(\n    x = c(X = 1, Y = 3, Z = 2),\n    y = c(X = 1, Y = 1, Z = 2)\n  )\n)\n\nbasic_dag_plot <- basic_dag |> \n  tidy_dagitty() |> \n  mutate(var_type = case_when(\n    name == \"X\" ~ \"Exposure\",\n    name == \"Y\" ~ \"Outcome\",\n    str_detect(name, \"Z\") ~ \"Confounder\"\n  )) |> \n  mutate(var_label = case_match(name,\n    \"X\" ~ \"Treatment\",\n    \"Y\" ~ \"Outcome\",\n    \"Z\" ~ \"Age\"\n  ))\n\nggplot(basic_dag_plot, aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_edges() +\n  geom_dag_point(aes(color = var_type), size = 12) +\n  geom_richtext(\n    aes(label = name), fontface = \"bold\", color = \"white\",\n    fill = NA, label.color = NA,\n    label.padding = grid::unit(c(3, 0, 0, 0), \"pt\")\n  ) + \n  geom_dag_text(\n    data = filter(basic_dag_plot, var_type != \"Confounder\"), aes(label = var_label), \n    nudge_y = -0.25, color = \"black\", size = 11, size.unit = \"pt\"\n  ) +\n  geom_dag_text(\n    data = filter(basic_dag_plot, var_type == \"Confounder\"), aes(label = var_label), \n    nudge_y = 0.26, color = \"black\", size = 11, size.unit = \"pt\"\n  ) +\n  scale_color_manual(values = clrs[c(4, 1, 6)], guide = \"none\") +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![DAG showing that age confounds the relationship between treatment and outcome](index_files/figure-html/fig-dag-basic-1.png){#fig-dag-basic fig-align='center' width=70%}\n:::\n:::\n\n\nThere are lots of ways to adjust for age here (there are whole textbooks about this; matching, inverse probability weighting, etc.). One simple way is to stratify by age and find the sum of weighted averages for old and young people, like this:\n\n$$\n\\text{ATE} = (\\pi_\\text{Old} \\times \\text{Effect}_\\text{Old}) + (\\pi_\\text{Young} \\times \\text{Effect}_\\text{Young})\n$$\n\nWith the data from the table, we get:\n\n$$\n\\begin{aligned}\n\\text{Effect}_\\text{Stratified} &= (\\pi_\\text{Treated} \\times \\bar{Y}_\\text{Treated}) - (\\pi_\\text{Untreated} \\times \\bar{Y}_\\text{Untreated}) \\\\[20pt]\n\\text{Effect}_\\text{Old} &= \\frac{80 + 75 + 85}{3} - \\frac{60}{1} &&= 20 \\\\\n\\text{Effect}_\\text{Young} &= \\frac{75}{1} - \\frac{80 + 100 + 80}{3} &&= -11.667 \\\\[20pt]\n\\text{ATE} &= (\\frac{4}{8} \\times 20) + (\\frac{4}{8} \\times -11.667) &&= 4.1667\n\\end{aligned}\n$$\n\n4.1667 isn't quite the true ATE of 5, but it's surprisingly close! If we had more than 8 rows of data, we'd get even closer (as long as age was really truly the only confounder).\n\n# Moving beyond the ATE\n\nWalking through a table like this is a useful exercise. It illustrates how individual causal effects are unobservable. It shows how we could theoretically find the average treatment effect of some intervention. It highlights the role selection bias and confounding play in distorting causal effects. It points to ways of accounting for confounding through statistical adjustment.\n\nBut for me personally, that's about all the utility I've gotten out of tables like this. One aesthetic reason is that these numbers are all really generic—people get an outcome of 80 or 60 or whatever, but 80 or 60 *what*? It's left up to the reader's imagination.\n\nMore importantly, though, I've always figured that the ATT and ATU that you calculate from these kinds of tables were extra peripheral estimands that you found on your way to calculating the ATE, and that all you should really care about is the ATE.\n\n**But that's wrong!**\n\nSo to rectify this, let's explore the nuances of different flavors of treatment effects using a more involved potential outcomes dataset that's more realistic, based on a hypothetical international development intervention designed to reduce the risk of malaria through the use of anti-mosquito bed nets.[^net-update] The data is observational and non-experimental—people choose to use the nets or not based on personal preferences. In this case, income and health confound the net → malaria risk relationship: income influences health, and both income and health influence the choice to use a net and overall malaria risk. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nmosquito_dag <- dagitty('\ndag {\n\"X\" [exposure,pos=\"1,1\"]\n\"Y\" [outcome,pos=\"4,1\"]\n\"Z<sub>1</sub>\" [pos=\"2,2\"]\n\"Z<sub>2</sub>\" [pos=\"3,2\"]\n\"Z<sub>2</sub>\" -> \"Y\"\n\"Z<sub>2</sub>\" -> \"X\"\n\"Z<sub>1</sub>\" -> \"Y\"\n\"Z<sub>1</sub>\" -> \"Z<sub>2</sub>\"\n\"Z<sub>1</sub>\" -> \"X\"\n\"X\" -> \"Y\"\n}')\n\ndag_plot <- mosquito_dag |> \n  tidy_dagitty() |> \n  mutate(var_type = case_when(\n    name == \"X\" ~ \"Exposure\",\n    name == \"Y\" ~ \"Outcome\",\n    str_detect(name, \"Z\") ~ \"Confounder\"\n  )) |> \n  mutate(var_label = case_match(name,\n    \"X\" ~ \"Mosquito net\",\n    \"Y\" ~ \"Malaria risk\",\n    \"Z<sub>1</sub>\" ~ \"Income\",\n    \"Z<sub>2</sub>\" ~ \"Health\"\n  ))\n\nggplot(dag_plot, aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_edges() +\n  geom_dag_point(aes(color = var_type), size = 12) +\n  geom_richtext(\n    aes(label = name), fontface = \"bold\", color = \"white\",\n    fill = NA, label.color = NA,\n    label.padding = grid::unit(c(3, 0, 0, 0), \"pt\")\n  ) + \n  geom_dag_text(\n    data = filter(dag_plot, var_type != \"Confounder\"), aes(label = var_label), \n    nudge_y = -0.15, color = \"black\", size = 11, size.unit = \"pt\"\n  ) +\n  geom_dag_text(\n    data = filter(dag_plot, var_type == \"Confounder\"), aes(label = var_label), \n    nudge_y = 0.16, color = \"black\", size = 11, size.unit = \"pt\"\n  ) +\n  scale_color_manual(values = clrs[c(4, 1, 6)], guide = \"none\") +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![DAG showing the relationship between mosquito net use and malaria risk, confounded by health and income](index_files/figure-html/fig-dag-mosquito-1.png){#fig-dag-mosquito fig-align='center' width=90%}\n:::\n:::\n\n\n[^net-update]: I used a similar dataset [back in this blog post](https://www.andrewheiss.com/blog/2020/12/01/ipw-binary-continuous/index.html#binary-treatments), and I use similar data in my class too; this version is new and improved though, with more explicit confounding and differences between the ATE, ATT, and ATU built in.\n\n**In this dataset, the true ATE is −15.** Using a bed net causes a 15-unit decrease in malaria risk across the whole population on average.\n\nIn the interest of space, I've hidden the data generation code below. You can also download a CSV version of it here if you want to follow along but not run all the code:\n\n- [{{< fa file-csv >}} `mosquito_nets_v2.csv`](mosquito_nets_v2.csv)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code for generating synthetic mosquito net data\"}\nwithr::with_seed(1234, {\n  n <- 1500\n  \n  nets <- tibble(\n    # Generate exogenous variables\n    id = 1:n,\n    income = rnorm(n, 500, 100)\n  ) |> \n    # Generate health, which depends on income\n    mutate(\n      health = (0.1 * income) + rnorm(n, 0, 10),\n      health = pmin(pmax(health, 0), 100)  # Force values to 0-100 range\n    ) |> \n    # Generate net usage (treatment), which depends on health and income\n    mutate(\n      # Make people with high health and high income a lot more likely to\n      # self-select into treatment\n      income_high = income > quantile(income, 0.8),\n      health_high = health > quantile(health, 0.8),\n      \n      # Create latent propensity scores based on logit formula\n      net_prob = plogis(\n        -3 + (income / 300) + (health / 40) + \n          (0.9 * income_high) + (0.5 * health_high)),\n      \n      # Assign to treatment\n      net = rbinom(n, 1, \n        # Fancy little trick---increase the latent propensity score by 5\n        # percentage points for people already more likely (i.e. p > 50%) to\n        # receive treatment and decrease the propensity score by 8 percentage\n        # points for those already less likely to receive treatment\n        prob = ifelse(\n          net_prob > 0.5, \n          pmin(net_prob + 0.05, 0.98), \n          pmax(net_prob - 0.08, 0.02))\n        )\n    ) |> \n    # Generate potential and actual outcomes\n    mutate(\n      # Individual outcomes in a world where individuals are not treated\n      malaria_risk_0 = 90 + (-0.2 * health) + (-0.05 * income) + rnorm(n, 0, 6),\n      malaria_risk_0 = pmin(pmax(malaria_risk_0, 0), 100),  # Force values to 0-100\n      \n      # Individual outcomes in a world where individuals are treated\n      # Basically risk_0 + a baseline treatment effect + extra treatment effect\n      # boosts because of income and health\n      malaria_risk_1 = malaria_risk_0 - \n        rnorm(n, 3, 1) - (0.015 * income) - (0.09 * health),\n      malaria_risk_1 = pmin(pmax(malaria_risk_1, 0), 100),  # Force values to 0-100\n      \n      # Round stuff\n      malaria_risk_0 = round(malaria_risk_0, 1),\n      malaria_risk_1 = round(malaria_risk_1, 1),\n      \n      ice = malaria_risk_1 - malaria_risk_0,\n      \n      # Actual realized outcome\n      malaria_risk = ifelse(net == 1, malaria_risk_1, malaria_risk_0)\n    ) |> \n    # Round more stuff\n    mutate(across(c(income, health), ~round(., 0))) |> \n    # Only keep some columns\n    select(\n      id, income, income_high, health, health_high, net,\n      starts_with(\"malaria\"), ice\n    )\n})\n\nwrite_csv(nets, \"mosquito_nets_v2.csv\")\n```\n:::\n\n\nWe have four main variables in this data:\n\n- **Net use** *(Treatment)*: Binary 0/1, TRUE/FALSE variable indicating if the person uses a bed net.\n- **Malaria risk** *(Outcome)*: Scale from 0–100, with higher values representing greater risk.\n- **Income** *(Confounder)*: Weekly income, measured in dollars. Higher income causes a higher probability of using a net; people above the 80th percentile get an extra boost in probability.\n- **Health** *(Confounder)*: Health status, scale from 0–100, with higher values representing better health. Better health causes a higher probability of using a net; people above the 80th percentile get an extra boost in probability.\n\n@tbl-nets-po shows a small excerpt of the data, with people using nets highlighted in yellow to mimic standard example potential outcome tables like @tbl-basic-po.\n\n\n::: {#tbl-nets-po .cell .no-stripe layout-align=\"center\" tbl-cap='Potential outcomes, individual causal effects, and realized outcomes for synthetic mosquito net data'}\n\n```{.r .cell-code  code-fold=\"true\"}\nexcerpt <- nets |> \n  slice(c(3, 14, 15, 29, 4, 35, 37, 73)) |> \n  arrange(id)\n\nexcerpt |> \n  add_row(id = NA) |> \n  select(\n    id, income, health, net, \n    malaria_risk_1, malaria_risk_0, ice, malaria_risk\n  ) |> \n  gt() |> \n  sub_missing(missing_text = \"…\") |>\n  fmt_number(\n    columns = c(starts_with(\"malaria_risk\"), ice),\n    decimals = 1\n  ) |> \n  fmt_number(columns = c(income, health), decimals = 0) |> \n  \n  # Column labels\n  cols_label(\n    id = \"ID\",\n    income = md(\"$Z_{1_i}$\"),\n    health = md(\"$Z_{2_i}$\"),\n    net = md(\"$X_i$\"),\n    malaria_risk_0 = md(\"$Y^0_i$\"),\n    malaria_risk_1 = md(\"$Y^1_i$\"),\n    malaria_risk = md(\"$Y_i$\"),\n    ice = md(\"$Y^1_i - Y^0_i$\")\n  ) |>\n  \n  # Level 1 spanner labels\n  tab_spanner(\n    label = \"Income\", columns = income, \n    level = 1, id = \"level1_a\"\n  ) |> \n  tab_spanner(\n    label = \"Health\", columns = health, \n    level = 1, id = \"level1_b\"\n  ) |> \n  tab_spanner(\n    label = \"Net use\", columns = net, \n    level = 1, id = \"level1_c\"\n  ) |> \n  tab_spanner(\n    label = \"Potential outcomes\",\n    columns = c(malaria_risk_1, malaria_risk_0),\n    level = 1, id = \"level1_d\"\n  ) |> \n  tab_spanner(\n    label = \"ICE or \\\\(\\\\delta_i\\\\)\", columns = ice, \n    level = 1, id = \"level1_e\"\n  ) |> \n  tab_spanner(\n    label = \"Outcome\", columns = malaria_risk, \n    level = 1, id = \"level1_f\"\n  ) |> \n  \n  # Level 2 spanner labels\n  tab_spanner(\n    label = \"Confounders\",\n    columns = c(income, health),\n    level = 2, id = \"level2_a\"\n  ) |> \n  tab_spanner(\n    label = \"Treatment\", columns = net, \n    level = 2, id = \"level2_b\"\n  ) |> \n  tab_spanner(\n    label = \"Unobservable\",\n    columns = c(malaria_risk_1, malaria_risk_0, ice), \n    level = 2, id = \"level2_c\"\n  ) |> \n  tab_spanner(\n    label = \"Realized\", columns = malaria_risk, \n    level = 2, id = \"level2_d\") |> \n  \n  # Style stuff\n  tab_style(\n    style = cell_text(align = \"center\"),\n    locations = cells_column_labels()\n  ) |> \n  tab_style(\n    style = cell_text(align = \"center\"),\n    locations = cells_body()\n  ) |> \n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = list(\n      cells_column_spanners(spanners = starts_with(\"level1\")),\n      cells_column_labels(columns = \"id\")\n    )\n  ) |> \n  tab_style(\n    style = cell_text(style = \"italic\"),\n    locations = cells_column_spanners(spanners = starts_with(\"level2\"))\n  ) |> \n  \n  tab_style(\n    style = list(\n      cell_fill(color = clrs[4], alpha = 0.5)\n    ),\n    locations = cells_body(rows = net == 1)\n  ) |> \n  tab_footnote(\n    footnote = \"ICE = individual causal effect\",\n    locations = cells_column_spanners(spanners = \"level1_e\")\n  ) |> \n  opt_footnote_marks(marks = \"standard\") |> \n  opt_horizontal_padding(scale = 3) |> \n  opt_table_font(font = \"Jost\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ovoyznostn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ovoyznostn table {\n  font-family: Jost, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ovoyznostn thead, #ovoyznostn tbody, #ovoyznostn tfoot, #ovoyznostn tr, #ovoyznostn td, #ovoyznostn th {\n  border-style: none;\n}\n\n#ovoyznostn p {\n  margin: 0;\n  padding: 0;\n}\n\n#ovoyznostn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ovoyznostn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ovoyznostn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ovoyznostn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 15px;\n  padding-right: 15px;\n  overflow-x: hidden;\n}\n\n#ovoyznostn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ovoyznostn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ovoyznostn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ovoyznostn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ovoyznostn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ovoyznostn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ovoyznostn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ovoyznostn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ovoyznostn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ovoyznostn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ovoyznostn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#ovoyznostn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n  vertical-align: top;\n}\n\n#ovoyznostn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ovoyznostn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ovoyznostn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#ovoyznostn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ovoyznostn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#ovoyznostn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ovoyznostn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#ovoyznostn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ovoyznostn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#ovoyznostn .gt_left {\n  text-align: left;\n}\n\n#ovoyznostn .gt_center {\n  text-align: center;\n}\n\n#ovoyznostn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ovoyznostn .gt_font_normal {\n  font-weight: normal;\n}\n\n#ovoyznostn .gt_font_bold {\n  font-weight: bold;\n}\n\n#ovoyznostn .gt_font_italic {\n  font-style: italic;\n}\n\n#ovoyznostn .gt_super {\n  font-size: 65%;\n}\n\n#ovoyznostn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ovoyznostn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ovoyznostn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ovoyznostn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ovoyznostn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ovoyznostn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ovoyznostn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ovoyznostn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"colgroup\" id=\"Confounders\">\n        <span class=\"gt_column_spanner\">Confounders</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Treatment\">\n        <span class=\"gt_column_spanner\">Treatment</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"colgroup\" id=\"Unobservable\">\n        <span class=\"gt_column_spanner\">Unobservable</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Realized\">\n        <span class=\"gt_column_spanner\">Realized</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" style=\"text-align: center; font-weight: bold;\" scope=\"col\" id=\"ID\">ID</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Income\">\n        <span class=\"gt_column_spanner\">Income</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Health\">\n        <span class=\"gt_column_spanner\">Health</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Net use\">\n        <span class=\"gt_column_spanner\">Net use</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"Potential outcomes\">\n        <span class=\"gt_column_spanner\">Potential outcomes</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"ICE or \\(\\delta_i\\)&lt;span class=&quot;gt_footnote_marks gt_asterisk&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;*&lt;/sup&gt;&lt;/span&gt;\">\n        <span class=\"gt_column_spanner\">ICE or \\(\\delta_i\\)<span class=\"gt_footnote_marks gt_asterisk\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>*</sup></span></span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Outcome\">\n        <span class=\"gt_column_spanner\">Outcome</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Z_{1_i}$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Z_{1_i}\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Z_{1_i}$\"><div class='gt_from_md'><p>\\(Z_{1_i}\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Z_{2_i}$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Z_{2_i}\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Z_{2_i}$\"><div class='gt_from_md'><p>\\(Z_{2_i}\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$X_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(X_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$X_i$\"><div class='gt_from_md'><p>\\(X_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y^1_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y^1_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y^1_i$\"><div class='gt_from_md'><p>\\(Y^1_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y^0_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y^0_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y^0_i$\"><div class='gt_from_md'><p>\\(Y^0_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y^1_i - Y^0_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y^1_i - Y^0_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y^1_i - Y^0_i$\"><div class='gt_from_md'><p>\\(Y^1_i - Y^0_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y_i$\"><div class='gt_from_md'><p>\\(Y_i\\)</p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">3</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">608</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">54</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">34.9</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">52.7</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">−17.8</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">34.9</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">4</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">265</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">21</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">73.0</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">82.8</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">−9.8</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">82.8</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">14</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">506</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">58</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">22.5</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">39.4</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">−16.9</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">22.5</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">15</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">596</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">62</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">43.0</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">59.0</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">−16.0</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">43.0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">29</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">498</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">61</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">40.0</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">55.6</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">−15.6</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">40.0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">35</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">337</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">42</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">57.6</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">68.0</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">−10.4</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">68.0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">37</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">282</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">28</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">50.5</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">59.4</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">−8.9</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">59.4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">73</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">463</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">37</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">47.9</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">59.4</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">−11.5</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">59.4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"malaria_risk_1\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"malaria_risk_0\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"ice\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"8\"><span class=\"gt_footnote_marks gt_asterisk\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>*</sup></span> ICE = individual causal effect</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nLet's use this data to explore and calculate three different estimands from @GreiferStuart:2023: the ATE, the ATT, and the ATU. For each estimand, we'll do this:\n\n1. Give a plain translation of what the estimand measures and explanation about why we would care about it\n2. Calculate the estimand using the true-but-unobservable individual causal effects (ICE), or $\\delta$\n3. Calculate the estimand using propensity score-based weighting and g-computation\n\n# Plain translations and true values\n\nHere's what the synthetic `nets` data looks like—we have columns for each of the columns in @tbl-nets-po, as well as some indicators for whether income and health are above the 80th percentile:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnets |> glimpse()\n## Rows: 1,500\n## Columns: 10\n## $ id             <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, …\n## $ income         <dbl> 379, 528, 608, 265, 543, 551, 443, 445, 444, 411, 452, 400, 422, 506, 596, 489, 449, 409, 416, 742, 513, 451, 456, 546, 431, 355, 557, 398, 498, 406, 610, 452, 429, 450, 337, 383, 282, 366, 471, 453, 645, 393, 414, 472, 401, 403, 389, 375, 448, 450, 319, 442, 389, 399, 484, …\n## $ income_high    <lgl> FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,…\n## $ health         <dbl> 56, 39, 54, 21, 51, 51, 49, 32, 39, 36, 41, 34, 54, 58, 62, 35, 74, 50, 54, 55, 49, 53, 49, 61, 49, 31, 53, 31, 61, 21, 58, 53, 41, 59, 42, 30, 28, 37, 50, 40, 58, 37, 51, 58, 34, 41, 29, 30, 39, 32, 12, 52, 43, 32, 58, 74, 41, 54, 78, 40, 51, 64, 41, 37, 29, 61, 48, 56, 79,…\n## $ health_high    <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…\n## $ net            <int> 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,…\n## $ malaria_risk_0 <dbl> 50.1, 59.4, 52.7, 82.8, 42.5, 54.0, 57.4, 68.8, 61.1, 54.9, 54.9, 66.6, 52.8, 39.4, 59.0, 60.7, 57.4, 54.9, 56.4, 29.2, 64.5, 61.4, 51.5, 52.0, 62.1, 60.1, 45.7, 67.7, 55.6, 70.3, 46.3, 53.9, 66.3, 58.5, 68.0, 51.7, 59.4, 61.6, 55.4, 64.7, 47.3, 59.0, 53.0, 68.9, 68.6, 64.5,…\n## $ malaria_risk_1 <dbl> 35.1, 42.9, 34.9, 73.0, 25.7, 38.9, 43.5, 56.1, 48.0, 41.1, 40.2, 53.0, 37.4, 22.5, 43.0, 46.6, 42.8, 41.1, 41.9, 10.8, 47.9, 46.6, 37.6, 34.8, 47.8, 47.7, 28.6, 54.4, 40.0, 60.2, 27.4, 39.7, 52.8, 42.6, 57.6, 39.8, 50.5, 50.6, 38.3, 52.9, 30.3, 48.5, 38.1, 54.4, 56.7, 51.2,…\n## $ malaria_risk   <dbl> 50.1, 59.4, 34.9, 82.8, 42.5, 38.9, 43.5, 56.1, 48.0, 41.1, 54.9, 66.6, 52.8, 22.5, 43.0, 60.7, 42.8, 54.9, 41.9, 29.2, 64.5, 61.4, 37.6, 52.0, 47.8, 60.1, 45.7, 67.7, 40.0, 70.3, 46.3, 39.7, 66.3, 42.6, 68.0, 39.8, 59.4, 61.6, 38.3, 64.7, 47.3, 59.0, 38.1, 54.4, 68.6, 51.2,…\n## $ ice            <dbl> -15.0, -16.5, -17.8, -9.8, -16.8, -15.1, -13.9, -12.7, -13.1, -13.8, -14.7, -13.6, -15.4, -16.9, -16.0, -14.1, -14.6, -13.8, -14.5, -18.4, -16.6, -14.8, -13.9, -17.2, -14.3, -12.4, -17.1, -13.3, -15.6, -10.1, -18.9, -14.2, -13.5, -15.9, -10.4, -11.9, -8.9, -11.0, -17.1, -11.…\n```\n:::\n\n\n## ATE\n\n\n\n\n\nThe average treatment effect (ATE) is what I've always assumed people always want to find when doing causal inference. It represents the effect of using bed nets across the whole population, even if people wouldn't ordinarily receive the treatment. It's a really broad estimand, so it's good for policies with a wide scope that might influence an entire population, like if a government is considering rolling out free or subsidized bed nets to everyone in the country.\n\nWe calculate this by taking the average of all individual causal effects: \n\n$$\n\\begin{aligned}\n\\text{ATE} &= E[\\delta_i] & \\text{ or} \\\\\n\\text{ATE} &= E[Y^1_i - Y^0_i]\n\\end{aligned}\n$$\n\nConceptually this is the same as imagining two hypothetical worlds: in Universe A we give everyone a bed net (even if they don't need it), and in Universe B we give nobody a bed net. We then calculate the difference in individual causal effects between those worlds.\n\nIf we look at just the eight rows of the bed net data in @tbl-nets-po, the ATE would be −13.36:\n\n$$\n\\frac{(-17.8) + (-9.8) + (-16.9) + (-16) + (-15.6) + (-10.4) + (-8.9) + (-11.5)}{8} = -13.36\n$$\n\nWe can calculate it with the full data by taking the average of the ICE column. It's −15.0, which is what I baked into the data:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnets |> \n  # I included the alternative versions here just to show that it's \n  # the average of Y1 - average of Y0\n  summarize(\n    ATE = mean(ice),\n    ATE_alt1 = mean(malaria_risk_1) - mean(malaria_risk_0),\n    ATE_alt2 = mean(malaria_risk_1 - malaria_risk_0)\n  )\n## # A tibble: 1 × 3\n##     ATE ATE_alt1 ATE_alt2\n##   <dbl>    <dbl>    <dbl>\n## 1 -15.0    -15.0    -15.0\n```\n:::\n\n\n## ATT\n\n\n\n\n\nThe average treatment effect on the treated (ATT) is narrower than the ATE, but (surprisingly!) is often more useful and policy relevant! It represents the effect of using bed nets, but only for people who use bed nets. That feels weird, so here are a few other examples:\n\n\n::: {#tbl-ate-vs-att .cell .no-stripe layout-align=\"center\" tbl-cap='Different types of causal effects that can be found as ATEs and ATTs'}\n\n```{.r .cell-code  code-fold=\"true\"}\ntribble(\n  ~ATE, ~ATT,\n  \"Effect of mosquito bed nets for everyone in the country\", \"Effect of mosquito bed nets for people who use bed nets\",\n  \"Effect of military service for typical applicants to the military\", \"Effect of military service for typical soldiers\",\n  \"Effect of a job training program on all residents in a state\", \"Effect of a job training program on everyone who used it\",\n  \"Effect of a new cancer medicine on everyone in the world\", \"Effect of a new cancer medicine on people with cancer\"\n) |> \n  gt() |> \n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_column_labels()\n  ) |> \n  tab_style(\n    style = cell_text(v_align = \"top\"),\n    locations = cells_body()\n  ) |> \n  tab_footnote(\n    footnote = html(\"Example via <a href='https://stats.stackexchange.com/a/455012/3025'>this Cross Validated response</a>\"),\n    locations = cells_body(columns = ATE, rows = 2)\n  ) |> \n  opt_footnote_marks(marks = \"standard\") |> \n  opt_horizontal_padding(scale = 3) |> \n  opt_table_font(font = \"Jost\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"sccfxenmua\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sccfxenmua table {\n  font-family: Jost, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sccfxenmua thead, #sccfxenmua tbody, #sccfxenmua tfoot, #sccfxenmua tr, #sccfxenmua td, #sccfxenmua th {\n  border-style: none;\n}\n\n#sccfxenmua p {\n  margin: 0;\n  padding: 0;\n}\n\n#sccfxenmua .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sccfxenmua .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sccfxenmua .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sccfxenmua .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 15px;\n  padding-right: 15px;\n  overflow-x: hidden;\n}\n\n#sccfxenmua .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sccfxenmua .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sccfxenmua .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sccfxenmua .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sccfxenmua .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sccfxenmua .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sccfxenmua .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sccfxenmua .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sccfxenmua .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sccfxenmua .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sccfxenmua .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#sccfxenmua .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n  vertical-align: top;\n}\n\n#sccfxenmua .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sccfxenmua .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sccfxenmua .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#sccfxenmua .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sccfxenmua .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#sccfxenmua .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sccfxenmua .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#sccfxenmua .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sccfxenmua .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#sccfxenmua .gt_left {\n  text-align: left;\n}\n\n#sccfxenmua .gt_center {\n  text-align: center;\n}\n\n#sccfxenmua .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sccfxenmua .gt_font_normal {\n  font-weight: normal;\n}\n\n#sccfxenmua .gt_font_bold {\n  font-weight: bold;\n}\n\n#sccfxenmua .gt_font_italic {\n  font-style: italic;\n}\n\n#sccfxenmua .gt_super {\n  font-size: 65%;\n}\n\n#sccfxenmua .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sccfxenmua .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sccfxenmua .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sccfxenmua .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sccfxenmua .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sccfxenmua .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sccfxenmua .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#sccfxenmua .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"ATE\">ATE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"ATT\">ATT</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"ATE\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Effect of mosquito bed nets for everyone in the country</td>\n<td headers=\"ATT\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Effect of mosquito bed nets for people who use bed nets</td></tr>\n    <tr><td headers=\"ATE\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Effect of military service for typical applicants to the military<span class=\"gt_footnote_marks gt_asterisk\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>*</sup></span></td>\n<td headers=\"ATT\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Effect of military service for typical soldiers</td></tr>\n    <tr><td headers=\"ATE\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Effect of a job training program on all residents in a state</td>\n<td headers=\"ATT\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Effect of a job training program on everyone who used it</td></tr>\n    <tr><td headers=\"ATE\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Effect of a new cancer medicine on everyone in the world</td>\n<td headers=\"ATT\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Effect of a new cancer medicine on people with cancer</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks gt_asterisk\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>*</sup></span> Example via <a href='https://stats.stackexchange.com/a/455012/3025'>this Cross Validated response</a></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe ATT feels a lot more useful for policy purposes. In medicine, it feels wrong to judge the effectiveness of a new drug based on the effect it would have on every person; in program evaluation, it feels wrong to judge the effectiveness of a training program on everyone, even if they wouldn't ever use it. \n\n**Both the ATE and the ATT are useful estimands for policy!**[^estimands-policy] \n\n[^estimands-policy]: See @HoImaiKing:2007 [p. 204] and @GreiferStuart:2023.\n\nConceptually, we can imagine two parallel worlds again: in Universe A we give everyone who's currently using a bed net a net, and in Universe B we take away those nets. We then calculate the difference between those worlds. The ATT thus represents the effect of *withholding* nets from those who would have used them [@GreiferStuart:2023, p. 7].\n\nBUT(!!!), thinking about the ATT feels wrong and weird—it feels like we're abandoning the whole idea of a control group and only looking at the treated group—which is why I've always been confused about this estimand. \n\nAnd I'm not alone! In forums and Q&A sites, people always wonder the same thing. Take [this comment to this response on Cross Validated](https://stats.stackexchange.com/a/308501/3025), for instance:\n\n> I'm a statistician, and I never have understood why someone would want to measure the ATT instead of the ATE. It's important to have a control group to account for regression to the mean effects & other factors - you're missing this when you use the ATT\n\nIt really does feel like we're only looking at treated people. Like this official formula here:\n\n$$\n\\begin{aligned}\n\\text{ATT} &= E[\\delta_i \\mid X_i = 1] & \\text{or} \\\\\n\\text{ATT} &= E[Y^1_i - Y^0_i \\mid X_i = 1]\n\\end{aligned}\n$$\n\nThat conditional $[\\dots \\mid X = 1]$ part says that we're only looking at treated people. And when we calculate it with hypothetical data, we really truly only look at the treated people. If we only look at the eight rows in @tbl-nets-po, the ATT would be −16.58:\n\n$$\n\\frac{(-17.8) + (-16.9) + (-16) + (-15.6)}{4} = -16.58\n$$\n\nWe can calculate it with the full data by taking the average of the ICE column after filtering the data so that we only look at people using a net. It's −16.3, higher than the ATE (implying selection bias).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnets |> \n  filter(net == 1) |> \n  summarize(ATT = mean(ice))\n## # A tibble: 1 × 1\n##     ATT\n##   <dbl>\n## 1 -16.3\n```\n:::\n\n\nThis is why the ATT is weird for me (and lots of other people). We're no longer finding the difference between treated and untreated people; we're looking only at treated people and somehow finding a causal effect, which feels wrong. \n\nI actually think that @tbl-nets-po here is making things more confusing for thinking about the ATT with observed data! Any causal effect is the difference between two numbers. Because we have time machine-based data, we're finding the difference between what would have happened in Universe A and Universe B, just for treated people. In real life, though, where we don't have a time machine, we can't find that difference. We still need to compare treated people with untreated people! We'll just do some extra statistical work to make the untreated people more comparable to the treated people.\n\nSo, **with hypothetical data we compare treated people to their parallel selves and we ignore the untreated; with real data we compare treated people to untreated people** (at least, in part; as we'll see below, we use information from the untreated people to estimate possible average causal effects for just the treated people).\n\n## ATU\n\n\n\n\n\nThe average treatment effect for the untreated (ATU) is just like the ATT, but in reverse. It represents the effect of using bed nets for people who aren't using them.\n\nLet's go back to the two parallel worlds: in Universe A we give everyone who's *not* currently using a bed net a net, and in Universe B we take away those nets. We then calculate the difference between those worlds. The ATU represents the effect of *expanding* treatment to those who did not receive it [@GreiferStuart:2023, p. 7].\n\nWe calculate this with hypothetical data by taking the average of the individual causal effects for untreated people:\n\n$$\n\\begin{aligned}\n\\text{ATU} &= E[\\delta_i \\mid X_i = 0] & \\text{or} \\\\\n\\text{ATU} &= E[Y^1_i - Y^0_i \\mid X_i = 0]\n\\end{aligned}\n$$\n\nIf we look at just @tbl-nets-po, the ATU would be −10.15:\n\n$$\n\\frac{(-9.8) + (-10.4) + (-8.9) + (-11.5)}{4} = -10.15\n$$\n\nWe can calculate it with the full data by taking the average of the ICE column after filtering the data so that we only look at people *not* using a net. It's −13.6, lower than the ATE (again, implying selection bias).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnets |> \n  filter(net == 0) |> \n  summarize(ATU = mean(ice))\n## # A tibble: 1 × 1\n##     ATU\n##   <dbl>\n## 1 -13.6\n```\n:::\n\n\nJust like the ATT, with hypothetical data we compare untreated people to their parallel selves and we ignore the treated. With real data, we'll compare untreated people to treated people, with some statistical shenanigans to make the two groups comparable and remove confounding and selection bias.\n\n\n# Selection bias and the ATE, ATT, and ATU\n\nBefore we calculate these different treatment effects with the realized outcomes instead of the hypothetical potential outcomes, let's look really quick at the practical difference between the true ATE, ATT, and ATU. All three estimands are useful for policymaking!\n\nThe ATE is −15, implying that mosquito nets cause a 15 point reduction in malaria risk for every person in the country. This includes people who live at high elevations where mosquitoes don't live, people who live near mosquito-infested swamps, people who are rich enough to buy [Bill Gates's mosquito laser](https://en.wikipedia.org/wiki/Mosquito_laser), and people who can't afford a net but would really like to use one. If we worked in the Ministry of Health and wanted to know if we should make a new national program that gave everyone a free bed net, the overall reduction in risk is −15, which is probably pretty good!\n\nThe ATT is −16.29, which is bigger than the ATE. The effect of net usage is bigger for people who are already using the nets. This is because of underlying systematic reasons, or selection bias. Those using nets want to use them because they need them more or can access them more easily—they might live in areas more prone to mosquitoes, or they can afford to buy their own nets, or something else. They know themselves and understand some notion of their personal individual causal effect and seek out nets. If we removed access to their nets, it would have a strong effect.\n\nThe ATU is −13.63, which is smaller than the ATE. The effect of net usage is smaller for people who aren't using the nets. Again, this is because of selection bias. Those not using nets are likely not using them for systematic reasons—they live far away from mosquitoes, they've received a future malaria vaccine, they have some other form of mosquito abatement, or something else. Because they can read their own minds, they know that mosquito net use won't do much for them personally, so they don't seek out nets. If we expanded access to nets to them, they wouldn't benefit as much.\n\nAnd one final note about the ATE—as we saw before, it includes both the ATT and the ATU. Because it's the average for everyone in the whole population, it's the sum of the weighted averages of these two estimands:\n\n$$\n\\text{ATE} = (\\pi_\\text{Net users} \\times \\text{ATT}) + (\\pi_\\text{Net non-users} \\times \\text{ATU})\n$$\n\nWe can confirm this with the data:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neffect_types <- nets |> \n  group_by(net) |> \n  summarize(\n    effect = mean(ice),\n    n = n()\n  ) |> \n  mutate(\n    prop = n / sum(n),\n    weighted_effect = effect * prop\n  ) |> \n  mutate(estimand = case_match(net, 0 ~ \"ATU\", 1 ~ \"ATT\"), .before = 1)\neffect_types\n## # A tibble: 2 × 6\n##   estimand   net effect     n  prop weighted_effect\n##   <chr>    <int>  <dbl> <int> <dbl>           <dbl>\n## 1 ATU          0  -13.6   715 0.477           -6.50\n## 2 ATT          1  -16.3   785 0.523           -8.52\n\neffect_types |> \n  summarize(ATE = sum(weighted_effect))\n## # A tibble: 1 × 1\n##     ATE\n##   <dbl>\n## 1 -15.0\n```\n:::\n\n\n\n# Finding these estimands with non-potential-outcome-based data\n\nSo far we've calculated the ATE, ATT, and ATU with data based on a time machine. In real life, we can only see this:\n\n\n::: {#tbl-nets-realized .cell .no-stripe layout-align=\"center\" tbl-cap='Observed version of @tbl-nets-po showing only the realized outcome'}\n\n```{.r .cell-code  code-fold=\"true\"}\nexcerpt |> \n  add_row(id = NA) |> \n  select(\n    id, income, health, net, malaria_risk\n  ) |> \n  gt() |> \n  sub_missing(missing_text = \"…\") |>\n  fmt_number(\n    columns = malaria_risk,\n    decimals = 1\n  ) |> \n  fmt_number(columns = c(income, health), decimals = 0) |> \n  \n  # Column labels\n  cols_label(\n    id = \"ID\",\n    income = md(\"$Z_{1_i}$\"),\n    health = md(\"$Z_{2_i}$\"),\n    net = md(\"$X_i$\"),\n    malaria_risk = md(\"$Y_i$\")\n  ) |>\n  \n  # Level 1 spanner labels\n  tab_spanner(\n    label = \"Income\", columns = income, \n    level = 1, id = \"level1_a_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Health\", columns = health, \n    level = 1, id = \"level1_b_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Net use\", columns = net, \n    level = 1, id = \"level1_c_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Outcome\", columns = malaria_risk, \n    level = 1, id = \"level1_d_obs\"\n  ) |> \n  \n  # Level 2 spanner labels\n  tab_spanner(\n    label = \"Confounders\",\n    columns = c(income, health),\n    level = 2, id = \"level2_a_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Treatment\", columns = net, \n    level = 2, id = \"level2_b_obs\"\n  ) |> \n  tab_spanner(\n    label = \"Realized\", columns = malaria_risk, \n    level = 2, id = \"level2_c_obs\") |> \n  \n  # Style stuff\n  tab_style(\n    style = cell_text(align = \"center\"),\n    locations = cells_column_labels()\n  ) |> \n  tab_style(\n    style = cell_text(align = \"center\"),\n    locations = cells_body()\n  ) |> \n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = list(\n      cells_column_spanners(spanners = starts_with(\"level1\")),\n      cells_column_labels(columns = \"id\")\n    )\n  ) |> \n  tab_style(\n    style = cell_text(style = \"italic\"),\n    locations = cells_column_spanners(spanners = starts_with(\"level2\"))\n  ) |> \n  \n  tab_style(\n    style = list(\n      cell_fill(color = clrs[4], alpha = 0.5)\n    ),\n    locations = cells_body(rows = net == 1)\n  ) |> \n  opt_horizontal_padding(scale = 3) |> \n  opt_table_font(font = \"Jost\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xgszuqdnoa\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xgszuqdnoa table {\n  font-family: Jost, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xgszuqdnoa thead, #xgszuqdnoa tbody, #xgszuqdnoa tfoot, #xgszuqdnoa tr, #xgszuqdnoa td, #xgszuqdnoa th {\n  border-style: none;\n}\n\n#xgszuqdnoa p {\n  margin: 0;\n  padding: 0;\n}\n\n#xgszuqdnoa .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xgszuqdnoa .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xgszuqdnoa .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xgszuqdnoa .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 15px;\n  padding-right: 15px;\n  overflow-x: hidden;\n}\n\n#xgszuqdnoa .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xgszuqdnoa .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xgszuqdnoa .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xgszuqdnoa .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xgszuqdnoa .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xgszuqdnoa .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xgszuqdnoa .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xgszuqdnoa .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xgszuqdnoa .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xgszuqdnoa .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xgszuqdnoa .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#xgszuqdnoa .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n  vertical-align: top;\n}\n\n#xgszuqdnoa .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xgszuqdnoa .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xgszuqdnoa .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#xgszuqdnoa .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xgszuqdnoa .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#xgszuqdnoa .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xgszuqdnoa .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#xgszuqdnoa .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xgszuqdnoa .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#xgszuqdnoa .gt_left {\n  text-align: left;\n}\n\n#xgszuqdnoa .gt_center {\n  text-align: center;\n}\n\n#xgszuqdnoa .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xgszuqdnoa .gt_font_normal {\n  font-weight: normal;\n}\n\n#xgszuqdnoa .gt_font_bold {\n  font-weight: bold;\n}\n\n#xgszuqdnoa .gt_font_italic {\n  font-style: italic;\n}\n\n#xgszuqdnoa .gt_super {\n  font-size: 65%;\n}\n\n#xgszuqdnoa .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xgszuqdnoa .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xgszuqdnoa .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xgszuqdnoa .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xgszuqdnoa .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xgszuqdnoa .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xgszuqdnoa .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xgszuqdnoa .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-style: italic; font-style: italic; font-style: italic;\" scope=\"colgroup\" id=\"Confounders\">\n        <span class=\"gt_column_spanner\">Confounders</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Treatment\">\n        <span class=\"gt_column_spanner\">Treatment</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-style: italic; font-style: italic; font-style: italic;\" scope=\"col\" id=\"Realized\">\n        <span class=\"gt_column_spanner\">Realized</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" style=\"text-align: center; font-weight: bold;\" scope=\"col\" id=\"ID\">ID</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Income\">\n        <span class=\"gt_column_spanner\">Income</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Health\">\n        <span class=\"gt_column_spanner\">Health</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Net use\">\n        <span class=\"gt_column_spanner\">Net use</span>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Outcome\">\n        <span class=\"gt_column_spanner\">Outcome</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Z_{1_i}$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Z_{1_i}\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Z_{1_i}$\"><div class='gt_from_md'><p>\\(Z_{1_i}\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Z_{2_i}$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Z_{2_i}\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Z_{2_i}$\"><div class='gt_from_md'><p>\\(Z_{2_i}\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$X_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(X_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$X_i$\"><div class='gt_from_md'><p>\\(X_i\\)</p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"text-align: center;\" scope=\"col\" id=\"&lt;div data-qmd=&quot;$Y_i$&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;\\(Y_i\\)&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd=\"$Y_i$\"><div class='gt_from_md'><p>\\(Y_i\\)</p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">3</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">608</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">54</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">34.9</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">4</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">265</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">21</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">82.8</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">14</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">506</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">58</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">22.5</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">15</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">596</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">62</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">43.0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">29</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">498</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">61</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">1</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center; background-color: rgba(255,204,61,0.5);\">40.0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">35</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">337</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">42</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">68.0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">37</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">282</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">28</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">59.4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">73</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">463</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">37</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">0</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">59.4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"income\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"health\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"net\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td>\n<td headers=\"malaria_risk\" class=\"gt_row gt_right\" style=\"text-align: center;\">…</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$\\delta_i$ is gone; we only have $Y_i$. Instead of comparing and finding the differences between individuals and their parallel selves, we need to find the differences between treated and untreated people *while removing the selection bias and confounding caused by income and health*.\n\nIn the initial example in @tbl-basic-po, there was just one confounder (old vs. young), and we adjusted for it by stratifying by age, combining the weighted averages for old and young people. Basic stratification like that is a lot harder to do here. Both income and health are continuous—we can't just find weighted averages of rich vs. poor and sick vs. healthy people. We've got to do something fancier to make comparable comparison groups, like matching or weighting. \n\nImportantly, **we have to match or weight in a way that is appropriate to the estimand we care about.** The matching procedure that we follow for finding the ATE can't be used for finding the ATT; the weighting process that we use for the ATU is different from what we use for the ATE. This is the main argument in @GreiferStuart:2023—the choice of estimand determines the process of statistical adjustment.\n\nNoah Greifer has two incredible parallel guides to doing this adjustment with both [weighting with {WeightIt}](https://ngreifer.github.io/WeightIt/articles/estimating-effects.html) and [matching with {MatchIt}](https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html). We'll illustrate this with propensity score weighting, but the same principles apply to matching (and the code is almost identical!)\n\nCovering the exact mechanics of probability weighting goes beyond the scope of this blog post! Check out these resources to learn more:\n\n- Chapter 12 in @HernanRobins:2024\n- Section 10.7 in @Heiss:2021\n- Lucy D'Agostino McGowan's [\"Understanding propensity score weighting\"](https://livefreeordichotomize.com/posts/2019-01-17-understanding-propensity-score-weighting/)\n- Noah Greifer's {WeightIt} vignette, [\"Estimating Effects After Weighting\"](https://ngreifer.github.io/WeightIt/articles/estimating-effects.html)\n- My [guide to matching and inverse probability weighting](https://evalsp24.classes.andrewheiss.com/example/matching-ipw.html) from my causal inference class and [the corresponding lecture video](https://evalsp24.classes.andrewheiss.com/content/07-content.html)\n\nIn general, with weighting we use confounders to predict the probability of choosing treatment, and then use these propensity scores to reweight the treated and untreated groups so that they resemble each other, thus removing any influence that the confounders have on the choice to select into treatment. My mental model of weighting is that we create pseudo-populations of treated and untreated people that feel like what would happen if we had randomly assigned everyone to treatment or control conditions—it's like creating fake treatment and control groups.\n\n## ATE\n\nTo find the ATE, we need to adjust both the treated and untreated groups so that they are comparable. The most common way to do this is to create inverse probability weights, where all treated people get a weight of $\\frac{1}{p_i}$ and all untreated people get a weight of $\\frac{1}{1 - p_i}$ (where $p_i$ refers to each person's propensity scores).\n\nPractically speaking, this gives more weight to more unusual and unexpected observations. For instance, someone with a high predicted probability (90%) of choosing to use a net who then uses a net isn't really notable and will have a low weight ($\\frac{1}{0.9}$, or 1.111). Someone else with a high probability (90% again) of choosing a net who *doesn't* use a net will have a high weight ($\\frac{1}{1 - 0.9}$, or 10). This makes it so that the should-have-probably-used-a-net person is more comparable to the corresponding untreated people.\n\nVisualization helps a lot with this intuition!\n\nFirst, we'll use logistic regression to calculate the predicted probabilities of using a net. We'll then create inverse probability weights with this formula, which uses the fact that `net` is stored as 0 or 1 to assign the correct treated vs. untreated weight:\n\n$$\n\\frac{\\text{Treatment}}{\\text{Propensity}} + \\frac{1 - \\text{Treatment}}{1 - \\text{Propensity}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Logistic regression model to predict net usage\nmodel_treatment <- glm(\n  net ~ income + health, \n  data = nets, \n  family = binomial(link = \"logit\")\n)\n\n# Plug original data into the model to generate predicted probabilities\n#\n# (Here I'm using broom::augment_columns(), but you can also use \n#  marginaleffects::predictions() or even base R's predict())\n# \n# Create a new column for the weights\nnets_with_weights <- augment_columns(\n  model_treatment,\n  data = nets,\n  type.predict = \"response\"\n) |> \n  rename(propensity = .fitted) |> \n  mutate(wts_ate = (net / propensity) + ((1 - net) / (1 - propensity)))\n\n# See if it worked\nnets_with_weights |> \n  select(id, income, health, net, malaria_risk, propensity, wts_ate)\n## # A tibble: 1,500 × 7\n##       id income health   net malaria_risk propensity wts_ate\n##    <int>  <dbl>  <dbl> <int>        <dbl>      <dbl>   <dbl>\n##  1     1    379     56     0         50.1     0.393     1.65\n##  2     2    528     39     0         59.4     0.427     1.75\n##  3     3    608     54     1         34.9     0.760     1.32\n##  4     4    265     21     0         82.8     0.0368    1.04\n##  5     5    543     51     0         42.5     0.622     2.65\n##  6     6    551     51     1         38.9     0.636     1.57\n##  7     7    443     49     1         43.5     0.412     2.43\n##  8     8    445     32     1         56.1     0.213     4.69\n##  9     9    444     39     1         48       0.286     3.50\n## 10    10    411     36     1         41.1     0.209     4.78\n## # ℹ 1,490 more rows\n```\n:::\n\n\nAlternatively, we can use the {WeightIt} package to do the same thing:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Get ATE-focused weights for the treatment model\nweights_ate <- weightit(\n  net ~ income + health, \n  data = nets, \n  method = \"glm\", \n  estimand = \"ATE\"\n)\n\n# Add the weights as a column in the data\nnets_with_weights$wts_ate_automatic <- weights_ate$weights\n\n# They're the same!\nnets_with_weights |> \n  select(id, wts_ate, wts_ate_automatic) |> \n  head()\n## # A tibble: 6 × 3\n##      id wts_ate wts_ate_automatic\n##   <int>   <dbl>             <dbl>\n## 1     1    1.65              1.65\n## 2     2    1.75              1.75\n## 3     3    1.32              1.32\n## 4     4    1.04              1.04\n## 5     5    2.65              2.65\n## 6     6    1.57              1.57\n```\n:::\n\n\nLet's copy [Lucy D'Agostino McGowan's approach](https://livefreeordichotomize.com/posts/2019-01-17-understanding-propensity-score-weighting/) and visualize the distribution of these propensity scores across treatment status:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_data_weights_ate <- tibble(\n  propensity = weights_ate$ps,\n  weight = weights_ate$weights,\n  treatment = weights_ate$treat\n)\n\nggplot() + \n  geom_histogram(data = filter(plot_data_weights_ate, treatment == 1), \n    bins = 50, aes(x = propensity, fill = \"Treated people\")) + \n  geom_histogram(data = filter(plot_data_weights_ate, treatment == 0), \n    bins = 50, aes(x = propensity, y = -after_stat(count), fill = \"Untreated people\")) +\n  geom_hline(yintercept = 0, color = \"white\", linewidth = 0.25) +\n  scale_x_continuous(labels = scales::label_percent()) +\n  scale_y_continuous(label = abs) +\n  scale_fill_manual(values = c(clrs[1], clrs[6]), guide = guide_legend(reverse = TRUE)) +\n  labs(x = \"Propensity\", y = \"Count\", fill = NULL) +\n  theme(\n    legend.position = \"top\",\n    legend.key.size = unit(0.65, \"lines\")\n  )\n```\n\n::: {.cell-output-display}\n![Mirrored histogram showing the distribution of propensity scores for treated and untreated people](index_files/figure-html/fig-propensity-treated-untreated-1.png){#fig-propensity-treated-untreated fig-align='center' width=90%}\n:::\n:::\n\n\nIn general, the people who used nets had a higher probability of using them, while the people who didn't use nets had a lower probability of using them. That's to be expected.\n\nBut there are some people who had a low probability of using nets who *did* use them, and some people who had a high probability of using nets who *did not* use them. That's curious and weird. These people are arguably very similar (i.e. with similar income and health), but for whatever reason, they didn't do what the model predicted they should do.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  geom_histogram(data = filter(plot_data_weights_ate, treatment == 1), \n    bins = 50, aes(x = propensity, fill = \"Treated people\")) + \n  geom_histogram(data = filter(plot_data_weights_ate, treatment == 0), \n    bins = 50, aes(x = propensity, y = -after_stat(count), fill = \"Untreated people\")) +\n  annotate(\n    geom = \"rect\", xmin = 0, xmax = 0.55, ymin = -1, ymax = 23,\n    fill = alpha(clrs[4], 0.1), color = clrs[4], linewidth = 1\n  ) +\n  annotate(\n    geom = \"text\", x = 0.01, y = 21.5, \n    label = \"Treated people who were\\nunlikely to be treated.\\nWeird!\",\n    color = clrs[3], fontface = \"bold\", hjust = 0, vjust = 1, lineheight = 1\n  ) +\n  annotate(\n    geom = \"rect\", xmin = 0.58, xmax = 1, ymin = 1, ymax = -27.5,\n    fill = alpha(clrs[4], 0.1), color = clrs[4], linewidth = 1\n  ) +\n  annotate(\n    geom = \"text\", x = 0.99, y = -26, \n    label = \"Weird!\\nUntreated people who\\nwere likely to be treated.\",\n    color = clrs[3], fontface = \"bold\", hjust = 1, vjust = 0, lineheight = 1\n  ) +\n  geom_hline(yintercept = 0, color = \"white\", linewidth = 0.25) +\n  scale_x_continuous(labels = scales::label_percent()) +\n  scale_y_continuous(label = abs) +\n  scale_fill_manual(values = c(clrs[1], clrs[6]), guide = guide_legend(reverse = TRUE)) +\n  labs(x = \"Propensity\", y = \"Count\", fill = NULL) +\n  theme(\n    legend.position = \"top\",\n    legend.key.size = unit(0.65, \"lines\")\n  )\n```\n\n::: {.cell-output-display}\n![Mirrored histogram showing \"weird\" parts of the population: treated people who were unlikely to be treated, and untreated people who were likely to be treated](index_files/figure-html/fig-propensity-weird-highlight-1.png){#fig-propensity-weird-highlight fig-align='center' width=90%}\n:::\n:::\n\n\nIf we scale everyone's importance according to their inverse probability weights, we can give more importance to these \"weird\" untreated-but-should-have-been-treated and treated-but-shouldn't-have-been-treated people, making them more balanced compared to their treated-and-should-have-been-treated and untreated-and-should-have-been-untreated counterparts. The fainter histogram here represents the adjusted and reweighted pseudo-populations of net users and non-net users. These two pseudo-populations are now free of the confounding coming from health and income and are arguably more comparable, acting more like randomized treatment and control groups.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  geom_histogram(data = filter(plot_data_weights_ate, treatment == 1), \n    bins = 50, aes(x = propensity, weight = weight, fill = \"Treated pseudo-population\")) + \n  geom_histogram(data = filter(plot_data_weights_ate, treatment == 0), \n    bins = 50, aes(x = propensity, weight = weight, y = -after_stat(count), fill = \"Untreated psuedo-population\")) +\n  geom_histogram(data = filter(plot_data_weights_ate, treatment == 1), \n    bins = 50, aes(x = propensity, fill = \"Treated people\")) + \n  geom_histogram(data = filter(plot_data_weights_ate, treatment == 0), \n    bins = 50, aes(x = propensity, y = -after_stat(count), fill = \"Untreated people\")) +\n  annotate(\n    geom = \"text\", x = 0.5, y = 60, label = \"More weight here\", \n    hjust = 0.5, fontface = \"bold\", color = clrs[3]\n  ) +\n  annotate(\n    geom = \"segment\", x = 0.48, xend = 0.17, y = 55, yend = 25, color = \"white\", \n    arrow = arrow(angle = 15, length = unit(0.5, \"lines\")), linewidth = 2.5\n  ) +\n  annotate(\n    geom = \"segment\", x = 0.48, xend = 0.17, y = 55, yend = 25, color = clrs[3], \n    arrow = arrow(angle = 15, length = unit(0.5, \"lines\")), linewidth = 0.5\n  ) +\n  annotate(\n    geom = \"segment\", x = 0.52, xend = 0.8, y = 55, yend = -20, color = \"white\", \n    arrow = arrow(angle = 15, length = unit(0.5, \"lines\")), linewidth = 2.5\n  ) +\n  annotate(\n    geom = \"segment\", x = 0.52, xend = 0.8, y = 55, yend = -20, color = clrs[3], \n    arrow = arrow(angle = 15, length = unit(0.5, \"lines\")), linewidth = 0.5\n  ) +\n  geom_hline(yintercept = 0, color = \"white\", linewidth = 0.25) +\n  scale_x_continuous(labels = scales::label_percent()) +\n  scale_y_continuous(label = abs) +\n  scale_fill_manual(\n    values = c(clrs[1], colorspace::lighten(clrs[1], 0.5), clrs[6], colorspace::lighten(clrs[6], 0.65)), \n    guide = guide_legend(reverse = FALSE, nrow = 2)) +\n  labs(x = \"Propensity\", y = \"Count\", fill = NULL) +\n  theme(\n    legend.position = \"top\",\n    legend.key.size = unit(0.65, \"lines\")\n  )\n```\n\n::: {.cell-output-display}\n![Mirrored histogram showing pseudo-populations of treated and untreated people that have been reweighted to be more comparable and unconfounded](index_files/figure-html/fig-propensity-weighted-ate-1.png){#fig-propensity-weighted-ate fig-align='center' width=90%}\n:::\n:::\n\n\nTo find the ATE using these weights, we can fit a regression model for the outcome. We'll then use an approach called [*g-computation*](https://ngreifer.github.io/WeightIt/articles/estimating-effects.html#g-computation) to find the marginal causal effect (i.e. the causal effect of flipping net from \"no\" to \"yes\"). G-computation is a neat approach that feels more like the original potential outcomes framework we looked at earlier. It involves a few steps:\n\n1. Fit a regression model predicting the outcome, like `lm(malaria_risk ~ net, weights = w_ate, ...)`\n2. Use the model to generate a set of predictions where we pretend that every person used a net (i.e. set `net = 1`)\n3. Use the model to generate a set of predictions where we pretend that every person did not use a net (i.e. set `net = 0`)\n4. Calculate the difference in the two sets of predictions to create a sort of predicted individual causal effect, then find the average of *that*. This is the ATE.\n\nThat looks really complicated and involved and feels like a lot of coding work, but {marignaleffects} makes this incredibly easy (there's even [a chapter dedicated to it in the documentation](https://marginaleffects.com/vignettes/gcomputation.html)). Basically, all we have to do is use `avg_comparisons(model_outcome, variables = list(net = 0:1))`, or even more simply `avg_comparisons(model_outcome, variables = \"net\")`. This will do all the work of setting everyone's treatment to 0, to 1, and finding the difference. We can do fancier things with it too, like finding robust and/or clustered standard errors, or [bootstrapping the standard errors](https://ngreifer.github.io/WeightIt/articles/estimating-effects.html#using-bootstrapping-to-estimate-confidence-intervals).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fit an outcome model using the inverse probability weights\nmodel_outcome_ate <- lm(\n  malaria_risk ~ net, \n  data = nets_with_weights, \n  weights = wts_ate_automatic\n)\n\n# Automatic g-computation with {marginaleffects}! This sets the \"net\" column to\n# each possible value of net (0 and 1) for the whole dataset, then calculates\n# the difference between the two sets of predictions\navg_comparisons(model_outcome_ate, variables = \"net\")\n## \n##  Term Contrast Estimate Std. Error     z Pr(>|z|)     S 2.5 % 97.5 %\n##   net    1 - 0    -14.7      0.559 -26.2   <0.001 500.6 -15.8  -13.6\n## \n## Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high \n## Type:  response\n```\n:::\n\n\n\n\n\nBased on our inverse probability weighting approach, the ATE from observational data (i.e. not using the unknowable individual potential outcomes) is −14.7, which is super close to the true ATE of −15.0!\n\n## ATT\n\nThat ATE shows the effect of the net program for *everyone*, even people who have no need for a net. If we're interested in making this a universal program, the ATE is useful. If we're interested in what the program is currently doing for people using it, or what would happen if we expanded it to just those not using it, we'd need to find the ATT or ATU instead.\n\nWe can do this with matching and weighting, but *we cannot use the same matching and weighting that we used to find the ATE.* When reweighting the data for estimating the ATT, we should not do anything that messes with the weights of the treated group. Since we're interested in the effect of the program on just the treated people, we need to create a pseudo-control group that looks like the treated group. There are lots of different ways to do this (and @GreiferStuart:2023 cover them). One common way is to give a weight of 1 to all the treated people and a weight of $\\frac{p_i}{1 - p_i}$ for all the untreated people.\n\nThe process is the same—fit a model that predicts if people use a net, use those predictions to generate weights, then fit an outcome model using those weights. With the ATT-specific weights, we'll create an untreated pseudo-population that is statistically comparable (and unconfounded) in relation to the actually treated population. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Get ATT-focused weights for the treatment model\nweights_att <- weightit(\n  net ~ income + health, \n  data = nets, \n  method = \"glm\", \n  estimand = \"ATT\"\n)\n\n# Add the weights as a column in the data\nnets_with_weights$wts_att <- weights_att$weights\n```\n:::\n\n\nOur fancy weighted histogram looks like this:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_data_weights_att <- tibble(\n  propensity = weights_att$ps,\n  weight = weights_att$weights,\n  treatment = weights_att$treat\n)\n\nggplot() + \n  geom_histogram(data = filter(plot_data_weights_att, treatment == 0), \n    bins = 50, aes(x = propensity, weight = weight, y = -after_stat(count), fill = \"Untreated psuedo-population\")) +\n  geom_histogram(data = filter(plot_data_weights_att, treatment == 1), \n    bins = 50, aes(x = propensity, fill = \"Treated people\")) + \n  geom_histogram(data = filter(plot_data_weights_att, treatment == 0), \n    bins = 50, alpha = 0.5, \n    aes(x = propensity, y = -after_stat(count), fill = \"Untreated people\")) +\n  geom_hline(yintercept = 0, color = \"white\", linewidth = 0.25) +\n  scale_x_continuous(labels = scales::label_percent()) +\n  scale_y_continuous(label = abs) +\n  scale_fill_manual(\n    values = c(clrs[1], \"grey50\", colorspace::lighten(clrs[6], 0.65)), \n    guide = guide_legend(reverse = FALSE, nrow = 2)) +\n  labs(x = \"Propensity\", y = \"Count\", fill = NULL) +\n  theme(\n    legend.position = \"top\",\n    legend.key.size = unit(0.65, \"lines\")\n  )\n```\n\n::: {.cell-output-display}\n![Mirrored histogram comparing the distribution of treated people with the reweighted pseudo-population of untreated people; because this is for the ATT, treated people were not reweighted](index_files/figure-html/fig-propensity-weighted-att-1.png){#fig-propensity-weighted-att fig-align='center' width=90%}\n:::\n:::\n\n\nThe treated people are untouched—they all have a weight of 1, and we don't mess with them. Untreated people with high probability of using a net are given more weight to make them look more like the treated people. \n\nFitting the outcome model is the same as finding the ATE—we'll just use the special ATT weights:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fit an outcome model using the ATT weights\nmodel_outcome_att <- lm(\n  malaria_risk ~ net, \n  data = nets_with_weights, \n  weights = wts_att\n)\n```\n:::\n\n\nThe main difference is that when we do the g-computation, we *only look at treated people*. Using only this part of the population, we'll set all their values to 1, then set all their values to 0, and then find the difference.\n\n**This is the key to finding the effect of the program only in the treated part of the population!** Remember how when we had access to everyone's individual causal effects, we were able to find the ATT by looking at the average of all the treated peoples' $\\delta$ column? G-computation lets us essentially recreate that process. Here's how it works:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Do g-computation *only* on treated observations\navg_comparisons(\n  model_outcome_att, \n  variables = \"net\", \n  newdata = filter(nets, net == 1)\n)\n## \n##  Term Contrast Estimate Std. Error     z Pr(>|z|)     S 2.5 % 97.5 %\n##   net    1 - 0    -17.6      0.497 -35.4   <0.001 907.4 -18.5  -16.6\n## \n## Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high \n## Type:  response\n```\n:::\n\n\n\n\nThe estimated observational ATT is −17.6, which is (1) bigger than the ATE, as expected, and (2) close-ish to the true ATT of −16.3!\n\n## ATU\n\nIf we're interested in what would happen if we expanded the program to people not using it, we can find the ATU. The process is the same as the ATT, just in reverse. We'll create a pseudo-population of net users by giving a weight of 1 to all untreated people and giving a weight of $\\frac{1-p_i}{p_i}$ to all treated people.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Get ATU-focused weights for the treatment model\nweights_atu <- weightit(\n  net ~ income + health, \n  data = nets, \n  method = \"glm\", \n  estimand = \"ATC\"  # WeightIt calls this ATC instead of ATU\n)\n\n# Add the weights as a column in the data\nnets_with_weights$wts_atu <- weights_atu$weights\n```\n:::\n\n\nHere's what that looks like as a weighted histogram:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nplot_data_weights_atu <- tibble(\n  propensity = weights_atu$ps,\n  weight = weights_atu$weights,\n  treatment = weights_atu$treat\n)\n\nggplot() + \n  geom_histogram(data = filter(plot_data_weights_atu, treatment == 1), \n    bins = 50, aes(x = propensity, weight = weight, fill = \"Treated pseudo-population\")) + \n  geom_histogram(data = filter(plot_data_weights_atu, treatment == 1), \n    bins = 50, alpha = 0.5, aes(x = propensity, fill = \"Treated people\")) + \n  geom_histogram(data = filter(plot_data_weights_atu, treatment == 0), \n    bins = 50, aes(x = propensity, y = -after_stat(count), fill = \"Untreated people\")) +\n  geom_hline(yintercept = 0, color = \"white\", linewidth = 0.25) +\n  scale_x_continuous(labels = scales::label_percent()) +\n  scale_y_continuous(label = abs) +\n  scale_fill_manual(\n    values = c(\"grey50\", colorspace::lighten(clrs[1], 0.5), clrs[6], colorspace::lighten(clrs[6], 0.65)), \n    guide = guide_legend(reverse = FALSE, nrow = 2)) +\n  labs(x = \"Propensity\", y = \"Count\", fill = NULL) +\n  theme(\n    legend.position = \"top\",\n    legend.key.size = unit(0.65, \"lines\")\n  )\n```\n\n::: {.cell-output-display}\n![Mirrored histogram comparing the distribution of untreated people with the reweighted pseudo-population of treated people; because this is for the ATU, untreated people were not reweighted](index_files/figure-html/fig-propensity-weighted-atu-1.png){#fig-propensity-weighted-atu fig-align='center' width=90%}\n:::\n:::\n\n\nThe low-probability net users get a lot more weight so that they're comparable to the untreated group.\n\nThe outcome model process is the same as before—we just use the ATU-specific weights. When doing the g-computation, we *only use untreated people*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fit an outcome model using the ATU weights\nmodel_outcome_atu <- lm(\n  malaria_risk ~ net, \n  data = nets_with_weights, \n  weights = wts_atu\n)\n\n# Do g-computation *only* on untreated observations\navg_comparisons(\n  model_outcome_atu, \n  variables = \"net\", \n  newdata = filter(nets, net == 0)\n)\n## \n##  Term Contrast Estimate Std. Error   z Pr(>|z|)     S 2.5 % 97.5 %\n##   net    1 - 0    -11.7      0.511 -23   <0.001 385.0 -12.7  -10.7\n## \n## Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high \n## Type:  response\n```\n:::\n\n\n\n\nThe estimated observational ATU is −11.7, which is (1) smaller than the ATE, as expected, and (2) close-ish to the true ATU of −13.6!\n\n## Summary\n\nFinally, let's show these estimands all together, with some basic interpretation of what they all mean:\n\n\n::: {#tbl-summary .cell layout-align=\"center\" tbl-cap='Summary of the three main estimands'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qojjlnbajx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qojjlnbajx table {\n  font-family: Jost, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qojjlnbajx thead, #qojjlnbajx tbody, #qojjlnbajx tfoot, #qojjlnbajx tr, #qojjlnbajx td, #qojjlnbajx th {\n  border-style: none;\n}\n\n#qojjlnbajx p {\n  margin: 0;\n  padding: 0;\n}\n\n#qojjlnbajx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qojjlnbajx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qojjlnbajx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qojjlnbajx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 15px;\n  padding-right: 15px;\n  overflow-x: hidden;\n}\n\n#qojjlnbajx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qojjlnbajx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qojjlnbajx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qojjlnbajx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qojjlnbajx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qojjlnbajx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qojjlnbajx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qojjlnbajx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qojjlnbajx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qojjlnbajx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qojjlnbajx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#qojjlnbajx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 15px;\n  padding-right: 15px;\n  vertical-align: top;\n}\n\n#qojjlnbajx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qojjlnbajx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qojjlnbajx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#qojjlnbajx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qojjlnbajx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#qojjlnbajx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 15px;\n  padding-right: 15px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qojjlnbajx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#qojjlnbajx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qojjlnbajx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 15px;\n  padding-right: 15px;\n}\n\n#qojjlnbajx .gt_left {\n  text-align: left;\n}\n\n#qojjlnbajx .gt_center {\n  text-align: center;\n}\n\n#qojjlnbajx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qojjlnbajx .gt_font_normal {\n  font-weight: normal;\n}\n\n#qojjlnbajx .gt_font_bold {\n  font-weight: bold;\n}\n\n#qojjlnbajx .gt_font_italic {\n  font-style: italic;\n}\n\n#qojjlnbajx .gt_super {\n  font-size: 65%;\n}\n\n#qojjlnbajx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qojjlnbajx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qojjlnbajx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qojjlnbajx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qojjlnbajx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qojjlnbajx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qojjlnbajx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qojjlnbajx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Estimand\">Estimand</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"True value\">True value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Estimated value\">Estimated value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Interpretation\">Interpretation</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Why care?\">Why care?</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimand\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">ATE</td>\n<td headers=\"true_value\" class=\"gt_row gt_center\" style=\"vertical-align: top;\">−15.0</td>\n<td headers=\"estimated_value\" class=\"gt_row gt_center\" style=\"vertical-align: top;\">−14.7</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Using a mosquito net reduces the risk of malaria by 14.7 points, on average across all people in the country</td>\n<td headers=\"why\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Helpful for understanding the effect of creating a widely applied policy or program, like rolling out subsidized mosquito nets for everyone in the country</td></tr>\n    <tr><td headers=\"estimand\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">ATT</td>\n<td headers=\"true_value\" class=\"gt_row gt_center\" style=\"vertical-align: top;\">−16.3</td>\n<td headers=\"estimated_value\" class=\"gt_row gt_center\" style=\"vertical-align: top;\">−17.6</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">People who currently use mosquito nets see a malaria risk reduction of 17.6 points, on average</td>\n<td headers=\"why\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Helpful for understanding the effect of net usage on people who actually use them; this shows what would happen if we withheld the program or took away everyone's nets</td></tr>\n    <tr><td headers=\"estimand\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">ATU</td>\n<td headers=\"true_value\" class=\"gt_row gt_center\" style=\"vertical-align: top;\">−13.6</td>\n<td headers=\"estimated_value\" class=\"gt_row gt_center\" style=\"vertical-align: top;\">−11.7</td>\n<td headers=\"interpretation\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">People who don't currently use mosquito nets would see a malaria risk reduction of 11.7 points, on average</td>\n<td headers=\"why\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Helpful for understanding the effect of net usage on people who don't use them right now; this shows what would happen if we expanded the program or gave nets to people without them</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"5\">Here, the fact that ATT &gt; ATE &gt; ATU implies selection bias; the program works more effectively among those who use it because they know it will help them</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n# What about other methods?\n\nAwesome. For me, at least, this all makes a lot more sense. The ATE is not the final goal of all causal inference methods. The ATT is also a completely good and valid and policy relevant estimand—often more important than the ATE. I've long been confused about what the ATT actually means, since it feels so weird—particularly in standard textbook potential outcomes tables. Finding the treatment effect just for the treated feels like we're abandoning the idea of a control or comparison group, but we're not! We're using information from untreated people to achieve balance, then applying that information to only the treated people through g-computation to approximate unobservable individual-level causal effects. We can thus find more specific causal effects using observational, non-experimental data.\n\nWhile working through all this, I discovered that I've actually been teaching methods that estimate the ATT without even knowing it. One super common method in econometrics and social science in general[^epi-diff-diff] is difference-in-differences. The causal effect you find from diff-in-diff research designs is the ATT, or the effect of an intervention on only the treated people. Diff-in-diff doesn't provide a population-level ATE.\n\n[^epi-diff-diff]: Though not in epidemiology, which is odd since [an epidemiologist essentially invented it](https://doi.org/10.1007/s40471-020-00245-2) [@CanigliaMurray:2020]!\n\nOther quasi-experimental methods like regression discontinuity and instrumental variables provide much more limited causal effects—they don't show the ATE, or the ATT, or the ATU. Instead, they provide a local average treatment effect (LATE), or a causal effect for a much narrower segment of the population. For regression discontinuity, we find the ATE for people close to an arbitrary threshold that causes a cutoff in treatment status; for instrumental variables we find the ATE for people who comply with the program assignment.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}