---
title: What I'm doing now
date: 2025-04-27
description: Andrew Heiss is working on a bunch of exciting and groundbreaking projects
published-title: Last updated
title-block-banner: "#771C6D"
toc: false
engine: knitr
freeze: false
---

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

As of April 27, 2025, I'm spending all my time on these things:

- Staying at home pretty much 24/7 (STILL) because of the COVID-19 pandemic
- Raising 6 kids (17.5, 15, 12.5, 9.5, 7.5, and 3) and trying to stay sane ([family blog](http://www.heissatopia.com/))
- Living in Atlanta and working as an assistant professor in the [Department of Public Management and Policy](https://aysps.gsu.edu/public-management-policy/) at the [Andrew Young School of Policy Studies](https://aysps.gsu.edu/) at [Georgia State University](https://www.gsu.edu/)
- Teaching [data visualization](https://datavizsp25.classes.andrewheiss.com/), [program evaluation](https://evalsp25.classes.andrewheiss.com/), [comparative public administration](https://compaf24.classes.andrewheiss.com/), [nonprofit management](https://nonprofitf22.classes.andrewheiss.com), and [microeconomics](https://econs24.classes.andrewheiss.com/) at the [Andrew Young School of Policy Studies](https://aysps.gsu.edu/) at [Georgia State University](https://www.gsu.edu/)
- Working as a part time data science mentor for [Posit Academy](https://posit.co/products/enterprise/academy/)
- Converting my dissertation into multiple articles and sending them out to journals + continuing [my research on authoritarianism and international NGOs](https://www.ingoresearch.org/)
- Working on several articles on NGO restrictions with [Suparna Chaudhry](http://www.suparnachaudhry.com/) and [Marc Dotson](https://marriottschool.byu.edu/directory/details?id=50683)
- Reading some sort of religiously themed text every day ([books](https://www.goodreads.com/review/list/2733632-andrew-heiss?shelf=religious))
